SELECT
ic.INS_COMPANY,
e.POLICY_FULL_NUM,
e.INS_COMP_DRAFT_POLICY_ID,
e.POLICY_CREATE_DATE,
e.POLICY_STATE_ID,
irj.INS_REQ_JOUR_ID,
e.POLICY_TERMIN_DATE,
XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('UTF-8')) AS XML_REQ,
XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.resp_body),NLS_CHARSET_ID('UTF-8')) AS XML_RESP
FROM RSA_EOSAGO.EPOLICY e
JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj ON e.POLICY_PROC_ID = ppj.POLICY_PROC_ID
JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON ppj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON e.INS_COMPANY_ID = ic.INS_COMPANY_ID
WHERE e.POLICY_NUMBER IN (

) ORDER BY e.POLICY_FULL_NUM;

SELECT * FROM BSI1.INS_REQUEST_JOUR irj WHERE irj.REQ_TYPE_ID IN (47) AND irj.BEG_DATE >= TRUNC(SYSDATE,'mm');

SELECT * FROM BSI1.INS_COMPANY ic 
  JOIN BSI1."USER" u ON ic.INS_COMPANY_ID = u.INS_COMPANY_ID
  WHERE ic.INS_COMPANY_ID = 20;