SELECT COUNT(KJ.INS_REQ_ID),KJ.INS_REQ_ID,KES.STATUS
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE KCSD.CREATE_DATE >= TRUNC(sysdate)
AND kcsd.POLICY_REC_ID IS NULL
AND kcsd.policy_unq_id IS NULL
AND kcsd.LOSS_ID IS NULL
AND kcsd.LOSS_DECISION_ID IS NULL
AND kcsd.KBM_PLUS_ID IS NULL
AND kcsd.KBM_JOUR_ID IS NULL
AND KCSD.IS_DECOUPLE_SUBJECT IS NULL
AND kcsd.POLICY_KASKO_REC_ID IS NULL
GROUP BY KJ.INS_REQ_ID,KES.STATUS
HAVING COUNT(KJ.INS_REQ_ID) > 1
;
--ORDER BY KCSD.CREATE_DATE DESC;
--WHERE  so.INN = '7709378229' AND kj.INS_REQ_ID IN (7904842702)
/*
AND kjv.VEHICLE_NORMALIZ_REC_ID IN (
'245347735',
'248805956',
'248805967',
'249380672',
'249446672',
'249446676',
'252387220'
)
*/
;

SELECT 
*
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' AND kj.INS_REQ_ID IN (7941691398)
/*
AND kjv.VEHICLE_NORMALIZ_REC_ID IN (
'245347735',
'248805956',
'248805967',
'249380672',
'249446672',
'249446676',
'252387220'
)
*/;


WITH TT1 AS (
SELECT 
kj.INS_REQ_ID,
so.INN,
so.ORG_NAME,
kjv.VEHICLE_NORMALIZ_REC_ID,
kjv.VEHICLE_LP_NORMALIZ_REC_ID,
kjv.JURIDICAL_VEHICLE_KBM_ID,
kjv.POLICY_REC_ID
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE so.INN = '7709378229' /*AND kes.STATUS = 3 AND kj.INS_REQ_ID IN (7609272273,7818817358)*/
AND kj.INS_REQ_ID IN (7904842702)
--AND kjv.VEHICLE_NORMALIZ_REC_ID = '194869642'
ORDER BY kjv.VEHICLE_NORMALIZ_REC_ID,kjv.VEHICLE_LP_NORMALIZ_REC_ID
),
TT2 AS (
SELECT
kj.INS_REQ_ID,
so.INN,
so.ORG_NAME,
kjv.VEHICLE_NORMALIZ_REC_ID,
kjv.VEHICLE_LP_NORMALIZ_REC_ID,
kjv.JURIDICAL_VEHICLE_KBM_ID,
kjv.POLICY_REC_ID
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE so.INN = '7709378229' /*AND kes.STATUS = 3 AND kj.INS_REQ_ID IN (7609272273,7818817358)*/
AND kj.INS_REQ_ID IN (7941691398)
ORDER BY kjv.VEHICLE_NORMALIZ_REC_ID,kjv.VEHICLE_LP_NORMALIZ_REC_ID
)
SELECT DISTINCT
TT1.INS_REQ_ID,
TT1.INN,
TT1.ORG_NAME,
TT1.VEHICLE_NORMALIZ_REC_ID,
TT1.VEHICLE_LP_NORMALIZ_REC_ID,
TT1.JURIDICAL_VEHICLE_KBM_ID,
TT1.POLICY_REC_ID,
TT2.INS_REQ_ID,
TT2.INN,
TT2.ORG_NAME,
TT2.VEHICLE_NORMALIZ_REC_ID,
TT2.VEHICLE_LP_NORMALIZ_REC_ID,
TT2.JURIDICAL_VEHICLE_KBM_ID,
TT2.POLICY_REC_ID
FROM TT1 JOIN TT2 ON TT1.VEHICLE_NORMALIZ_REC_ID = TT2.VEHICLE_NORMALIZ_REC_ID
WHERE TT1.JURIDICAL_VEHICLE_KBM_ID != TT2.JURIDICAL_VEHICLE_KBM_ID
UNION
SELECT DISTINCT
TT1.INS_REQ_ID,
TT1.INN,
TT1.ORG_NAME,
TT1.VEHICLE_NORMALIZ_REC_ID,
TT1.VEHICLE_LP_NORMALIZ_REC_ID,
TT1.JURIDICAL_VEHICLE_KBM_ID,
TT1.POLICY_REC_ID,
TT2.INS_REQ_ID,
TT2.INN,
TT2.ORG_NAME,
TT2.VEHICLE_NORMALIZ_REC_ID,
TT2.VEHICLE_LP_NORMALIZ_REC_ID,
TT2.JURIDICAL_VEHICLE_KBM_ID,
TT2.POLICY_REC_ID
FROM TT1 JOIN TT2 ON TT1.VEHICLE_LP_NORMALIZ_REC_ID = TT2.VEHICLE_LP_NORMALIZ_REC_ID
WHERE TT1.JURIDICAL_VEHICLE_KBM_ID != TT2.JURIDICAL_VEHICLE_KBM_ID;


SELECT 
*
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' AND kj.INS_REQ_ID IN (7904842702);

SELECT
ppj.*,
XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('UTF8'))
FROM rsa1.POLICY_PROCESS_JUR ppj 
JOIN rsa1.TRIP_IMP_JUR tij ON PPJ.TRIP_ID = TIJ.TRIP_ID
JOIN rsa1.INS_REQUEST_JUR irj ON TIJ.INS_REQ_ID = IRJ.INS_REQ_ID
WHERE PPJ.POLICY_REC_ID IN (
'691572187',
'660038112',
'660735522',
'660469377',
'644531484',
'644531493',
'635562232',
'679163361',
'679163362',
'679163352',
'708422959',
'708422793',
'706286575'
);


WITH TT1 AS (
SELECT 
kjv.POLICY_REC_ID
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' AND kj.INS_REQ_ID IN (7904842702)
), 
TT2 AS (
SELECT
PO.INS_COMPANY_ID||' '||po.INS_COMP_POLICY_ID
FROM rsa1.POLICY_OSAGO po
WHERE po.POLICY_REC_ID IN (
SELECT POLICY_REC_ID FROM TT1
)
)
SELECT
ic.INS_COMPANY,
ic.INSURER_ID,
PPJ.INS_COMP_POLICY_ID,
ppj.POLICY_REC_ID,
rs.REQ_STATUS,
PPJ.BSO_NUMBER,
ppj.PROC_QUEUE_DATE,
ppj.PROC_END_DATE,
HT.HANDLE_NAME,
irj.INS_REQ_ID,
XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('UTF8')) AS XML
FROM rsa1.POLICY_PROCESS_JUR ppj
JOIN rsa1.INS_COMPANY ic ON PPJ.INS_COMPANY_ID = IC.INS_COMPANY_ID
JOIN rsa1.REQUEST_STATUS rs ON PPJ.REQ_STATUS_ID = RS.REQ_STATUS_ID
JOIN rsa1.HANDLE_TYPE ht ON PPJ.HANDLE_TYPE_ID = HT.HANDLE_TYPE_ID
JOIN rsa1.TRIP_IMP_JUR tij ON ppj.TRIP_ID = tij.TRIP_ID
JOIN rsa1.INS_REQUEST_JUR irj ON TIJ.INS_REQ_ID = IRJ.INS_REQ_ID
WHERE PPJ.PROC_QUEUE_DATE 
BETWEEN 
TO_DATE('05.09.2019 14:54:20','dd.mm.yyyy hh24:mi:ss') 
AND 
TO_DATE('12.09.2019 10:28:55','dd.mm.yyyy hh24:mi:ss')
AND PPJ.INS_COMPANY_ID||' '||ppj.INS_COMP_POLICY_ID IN (
SELECT * FROM TT2
)
;

WITH TT1 AS (
SELECT DISTINCT 
so.INN
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE KCSD.CREATE_DATE >= TRUNC(sysdate)
AND kcsd.POLICY_REC_ID IS NULL
AND kcsd.policy_unq_id IS NULL
AND kcsd.LOSS_ID IS NULL
AND kcsd.LOSS_DECISION_ID IS NULL
AND kcsd.KBM_PLUS_ID IS NULL
AND kcsd.KBM_JOUR_ID IS NULL
AND KCSD.IS_DECOUPLE_SUBJECT IS NULL
AND kcsd.POLICY_KASKO_REC_ID IS NULL
)

SELECT *
FROM RSA2.TEMP_AUTO_CALC_KBM_2019 tack
WHERE tack.INN IN (
SELECT * FROM TT1
);