SELECT * FROM RSA_EGARANT.EVENT_LOG el
JOIN RSA_EGARANT.EVENT_TYPE et ON el.EVENT_TYPE_ID = et.EVENT_TYPE_ID  
WHERE el.APPLICATION_ID = '2342251052' ORDER by el.EVENT_DATE;

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj 
  JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
  WHERE VIN = 'XTK21043060063932'
  AND crj.PROC_BEG_DATE >= TO_DATE('17.05.2019 11:30','dd.mm.yyyy hh24:mi')
  AND crj.PROC_BEG_DATE < TO_DATE('17.05.2019 13:01','dd.mm.yyyy hh24:mi')
  ORDER by crj.DATE_REQUEST;


SELECT
  dp.VEHICLE_NON_IDENTIFYING_REC_ID,
  vni.VEH_CATEGORY,
  nm.NAME,
  nb.BRAND_NAME,
  vni.OTHER_MODEL_NAME,
  vni.OTHER_BRAND_NAME,
  v.VIN_ORIGIN,
  v.BODY_NUMBER_ORIGIN,
 v.LICENSE_PLATE_ORIGIN,
  v.CHASSIS_NUMBER_ORIGIN,
  vni.YEAR_ISSUE,
  vni.ENGINE_POWER,
  vni.MAX_WEIGHT,
  vni.CNT_PAS_PLACE,
  vni.VEH_DOC_SERIAL_ORIGIN,
  vni.VEH_DOC_NUMBER_ORIGIN,
  vni.VEH_DOC_DATE,
  vni.TO_DIAG_CARD_NUMBER,
  vni.TO_DIAG_CARD_DATE,
  nut.USE_TC
  FROM RSA_EGARANT.DRAFT_POLICY dp
  JOIN RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni ON dp.VEHICLE_NON_IDENTIFYING_REC_ID = vni.VEHICLE_NON_IDENTIFYING_REC_ID
  join RSA_EGARANT.VEHICLE v ON vni.VEHICLE_REC_ID = v.VEHICLE_REC_ID
  JOIN RSA_EGARANT.NSI_DIRECTORY_MOD_MODEL ndmm ON vni.MARK_MODEL_ID = ndmm.MOD_MODEL_ID
  JOIN RSA_EGARANT.NSI_MODEL nm ON ndmm.MODEL_ID = nm.MODEL_ID
  JOIN RSA_EGARANT.NSI_BRAND nb ON nm.BRAND_ID = nb.BRAND_ID
  JOIN (
  SELECT 
  MAX(v.BEG_DATE) bd,
  v.VEHICLE_REC_ID
  FROM RSA_EGARANT.VEHICLE v
  GROUP BY v.VEHICLE_REC_ID
  ) MAXVEH ON vni.VEHICLE_REC_ID = MAXVEH.VEHICLE_REC_ID
  JOIN RSA_EGARANT.NSI_DIRECTORY_MOD_MODEL ndmm ON vni.MARK_MODEL_ID = ndmm.MOD_MODEL_ID
  JOIN RSA_EGARANT.NSI_MODEL nm ON ndmm.MODEL_ID = nm.MODEL_ID
  JOIN RSA_EGARANT.NSI_BRAND nb ON nm.BRAND_ID = nb.BRAND_ID
  join RSA_EGARANT.NSI_USE_TC nut ON dp.USE_TC_ID = nut.USE_TC_ID
  where 1=1--vni.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
  AND v.BEG_DATE = MAXVEH.bd
  AND dp.APPLICATION_ID = '2342251052';

  SELECT *
  FROM RSA_EGARANT.DRAFT_POLICY dp
  JOIN RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni ON dp.VEHICLE_NON_IDENTIFYING_REC_ID = vni.VEHICLE_NON_IDENTIFYING_REC_ID
  --JOIN RSA_EGARANT.CHECK_LOG cl ON vni.CHECK_LOG_ID = cl.CHECK_LOG_ID
  --JOIN RSA_EGARANT.CHECK_TYPE ct ON cl.CHECK_TYPE_ID = ct.CHECK_TYPE_ID
  WHERE dp.APPLICATION_ID = '2342251052';

  SELECT * FROM RSA_EGARANT.CHECK_LOG cl
  JOIN RSA_EGARANT.CHECK_TYPE ct ON cl.CHECK_TYPE_ID = ct.CHECK_TYPE_ID
  WHERE cl.CHECK_LOG_ID = '32191518';

  SELECT * FROM RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni WHERE vni.VEHICLE_NON_IDENTIFYING_REC_ID = '13021271';

  SELECT * FROM RSA_EGARANT.NSI_REASON_REJECTION nrr WHERE nrr.TEXT LIKE '%тип%';