WITH KBMPARSE as (
SELECT
ic.INS_COMPANY,
irj.INS_REQ_ID,
irj.REQ_STATUS_ID,
irj.beg_date,
irj.END_DATE,
EXTRACTVALUE(value(TT1),'PhysicalPerson/PersonalDataInfo/Surname') HS,
EXTRACTVALUE(VALUE(TT1),'PhysicalPerson/PersonalDataInfo/Name')SERIAL,
EXTRACTVALUE(VALUE(TT1),'PhysicalPerson/PersonalDataInfo/Patronymic')NUMB
FROM RSA1.INS_REQUEST_JUR irj
JOIN RSA1.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID  
,
TABLE(XMLSEQUENCE(EXTRACT(XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('AL32UTF8')),'*:CalcRequest/CalcRequestValue/CalcKBMRequest/PhysicalPersons/PhysicalPerson')))TT1
--WHERE irj.BEG_DATE >= TRUNC(SYSDATE,'hh')
WHERE irj.BEG_DATE >= TO_DATE ('05.03.2019 08:43:00','dd.mm.yyyy hh24:mi:ss')
AND irj.BEG_DATE < TO_DATE ('05.03.2019 23:59:59','dd.mm.yyyy hh24:mi:ss')
--and irj.req_status_id = 3
AND ic.INS_COMPANY_ID = 269
AND irj.REQ_TYPE_ID = 1
)
SELECT
* 
from KBMPARSE k
  --where LOWER(k.HS) = LOWER('ÆÅËÅÇÎÃËÎ')
  WHERE LOWER(k.NUMB) = LOWER('ÍÈÊÎËÀÅÂÈ×')
  AND LOWER(k.HS) = LOWER('ÊÎÒÎÂ')
ORDER by k.BEG_DATE;

SELECT * FROM RSA1.INS_COMPANY ic WHERE ic.INS_COMPANY_ID = 262;

SELECT
  * 
  FROM RSA1.INS_REQUEST_JUR irj
  WHERE irj.BEG_DATE BETWEEN TO_DATE('05.03.2019 08:43','dd.mm.yyyy hh24:mi') AND TO_DATE('05.03.2019 12:45','dd.mm.yyyy hh24:mi')
  AND irj.INS_COMPANY_ID = 262 AND irj.REQ_TYPE_ID = 1 AND irj.REQ_STATUS_ID = 603;

SELECT v.* FROM RSA1.POLICY_OSAGO po 
  JOIN RSA1.VEHICLE_NON_IDENTIFYING vni ON po.VEHICLE_NON_IDENTIFYING_REC_ID = vni.VEHICLE_NON_IDENTIFYING_REC_ID
  JOIN RSA1.VEHICLE v ON vni.VEHICLE_REC_ID = v.VEHICLE_REC_ID
  WHERE po.BSO_NUMBER = '0040000622';