SELECT * FROM RSA_EOSAGO.PTS_DISTRIBUTION_OLD pdo;
SELECT * FROM RSA_EOSAGO.PTS_DISTRIBUTION_HISTORY_OLD pdho;
SELECT * FROM RSA_EOSAGO.PRINCIPAL_DETERMINE_OLD pdo;

SELECT * FROM RSA_EOSAGO.INS_COMPANY ic WHERE ic.INS_COMPANY LIKE '%Àäîíèñ%';

--352	ÎÎÎ "ÑÔ "Àäîíèñ"	20600000

SELECT
ic.INS_COMPANY,
pdo.CALCULATION_DATE,
pdo.PRINCIPAL_DETERMINE_CODE,
pdo1.PTS_NUMBER
FROM RSA_EOSAGO.PRINCIPAL_DETERMINE_OLD pdo
JOIN RSA_EOSAGO.PTS_DISTRIBUTION_OLD pdo1 ON pdo.PRINCIPAL_DETERMINE_ID = pdo1.PRINCIPAL_DETERMINE_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON pdo.INS_COMPANY_ID = ic.INS_COMPANY_ID
WHERE 1=1 --pdo.INS_COMPANY_ID = 352
AND pdo.CALCULATION_DATE = TRUNC(TO_DATE('19.12.2018','dd.mm.yyyy'),'iw')
AND pdo.PRINCIPAL_DETERMINE_CODE = 1
AND pdo1.PTS_NUMBER IN (
'019367'
)
union all
SELECT
ic.INS_COMPANY,
pdo.CALCULATION_DATE,
pdo.PRINCIPAL_DETERMINE_CODE,
pdo1.PTS_NUMBER
FROM RSA_EOSAGO.PRINCIPAL_DETERMINE_OLD pdo
JOIN RSA_EOSAGO.PTS_DISTRIBUTION_OLD pdo1 ON pdo.PRINCIPAL_DETERMINE_ID = pdo1.PRINCIPAL_DETERMINE_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON pdo.INS_COMPANY_ID = ic.INS_COMPANY_ID
WHERE 1=1 --pdo.INS_COMPANY_ID = 352
AND pdo.CALCULATION_DATE = TRUNC(TO_DATE('22.03.2019','dd.mm.yyyy'),'iw')
AND pdo.PRINCIPAL_DETERMINE_CODE = 1
AND pdo1.PTS_NUMBER IN (
'730326',
'700554'
)
UNION ALL
SELECT
ic.INS_COMPANY,
pdo.CALCULATION_DATE,
pdo.PRINCIPAL_DETERMINE_CODE,
pdho.PTS_NUMBER
FROM RSA_EOSAGO.PRINCIPAL_DETERMINE_OLD pdo
JOIN RSA_EOSAGO.PTS_DISTRIBUTION_HISTORY_OLD pdho ON pdo.PRINCIPAL_DETERMINE_ID = pdho.PRINCIPAL_DETERMINE_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON pdo.INS_COMPANY_ID = ic.INS_COMPANY_ID
WHERE 1=1 --pdo.INS_COMPANY_ID = 352
AND pdo.CALCULATION_DATE = TRUNC(TO_DATE('19.12.2018','dd.mm.yyyy'),'iw')
AND pdo.PRINCIPAL_DETERMINE_CODE = 1
AND pdho.PTS_NUMBER IN (
'019367',
'816946'
)
;

SELECT TRUNC(TO_DATE('11.03.2019','dd.mm.yyyy'),'iw') FROM DUAL d;

SELECT * FROM RSA_EOSAGO.PTS_DISTRIBUTION_HISTORY_OLD pdho WHERE pdho.PRINCIPAL_DETERMINE_ID IN (
  SELECT pdo.PRINCIPAL_DETERMINE_ID FROM RSA_EOSAGO.PRINCIPAL_DETERMINE_OLD pdo
WHERE pdo.CALCULATION_DATE >= TRUNC(TO_DATE('11.03.2019','dd.mm.yyyy'),'iw')
);

SELECT pdo.PRINCIPAL_DETERMINE_ID FROM RSA_EOSAGO.PRINCIPAL_DETERMINE_OLD pdo
WHERE pdo.CALCULATION_DATE >= TRUNC(TO_DATE('11.03.2019','dd.mm.yyyy'),'iw');