WITH COMPRO AS (
SELECT
INS_REQ_ID
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
WHERE so.INN = '5836683077' AND kes.STATUS = 3
)
SELECT 
*
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
WHERE so.INN = '5836683077'
AND kj.INS_REQ_ID NOT IN (
SELECT ins_req_id FROM COMPRO 
) ORDER BY kj.CREATE_DATE;

SELECT * FROM RSA2.KBM_JOUR kj WHERE kj.INS_REQ_ID IN (7343831646);

SELECT
*
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE so.INN = '6164077483' AND kes.STATUS = 3 AND kj.INS_REQ_ID IN (7167976919,7143836948);