SELECT
kj.INS_REQ_ID "ID расчета КБМ",
kes.CREATE_DATE "Дата расчета",
kjpc.ARITHMETIC_MEAN_KBM "Значение КБМ из расчета",
so.INN,
so.ORG_NAME,
so.IS_RESIDENT,
kes.STATUS,
kes.CREATE_DATE "Дата и время смены статуса"
FROM rsa2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA1.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
--LEFT JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE so.INN = '2339003248' ORDER BY kes.CREATE_DATE;
