SELECT * FROM RSA_EGARANT.INS_COMPANY ic JOIN "USER" u ON ic.INS_COMPANY_ID = u.INS_COMPANY_ID
WHERE ic.INS_COMPANY_ID = '265';

SELECT DISTINCT *
--ic.INS_COMPANY
FROM RSA_EGARANT.DRAFT_POLICY dp
JOIN RSA_EGARANT.INS_COMPANY ic ON dp.INS_COMPANY_ID = ic.INS_COMPANY_ID
--WHERE dp.DRAFT_POLICY_ID = '71'
--WHERE dp.application_id = '145363592';
WHERE dp.INS_COMPANY_ID = '217'
AND dp.END_DATE = TO_DATE('01.01.9000');

SELECT * FROM RSA_EGARANT.POLICY_SUBJ_INFO psi WHERE psi.END_DATE = TO_DATE('01.01.9000');
SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi --WHERE ROWNUM < 2
;

SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi 
JOIN RSA_EGARANT.POLICY_SUBJ_INFO psi ON pi.PERSONAL_INFO_ID = psi.POLICY_SUBJ_INFO_ID
JOIN RSA_EGARANT.DRAFT_POLICY dp ON psi.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
--JOIN RSA_EGARANT.SUBJECT_OSAGO so ON pi.PERSONAL_INFO_ID = so.PERSONAL_INFO_ID
WHERE subj_osago_rec_id = '151';

-------------------------------
SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi WHERE pi.PERSONAL_INFO_ID IN ('164','165','166');
SELECT * FROM RSA_EGARANT.POLICY_SUBJ_INFO psi; --WHERE psi.SUBJ_OSAGO_REC_ID IN ('164','165','166'); --AND psi.END_DATE = TO_DATE('01.01.9000');
SELECT * FROM RSA_EGARANT.DRAFT_POLICY dp ORDER by dp.DRAFT_POLICY_ID;
SELECT * FROM RSA_EGARANT.DRAFT_POLICY dp where dp.INS_COMP_DRAFT_POLICY_ID = 'RSA_145326109_05072017124147000';
SELECT * FROM RSA_EGARANT.HANDLE_TYPE ht WHERE ht.HANDLE_TYPE_ID = '0';

SELECT *
FROM RSA_EGARANT.PERSONAL_INFO pi 
JOIN RSA_EGARANT.SUBJECT_OSAGO so ON pi.PERSONAL_INFO_ID = so.PERSONAL_INFO_ID
LEFT JOIN RSA_EGARANT.SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
JOIN RSA_EGARANT.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
JOIN RSA_EGARANT.DRAFT_POLICY dp ON psi.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
WHERE dp.DRAFT_POLICY_ID = '1'
AND psi.END_DATE = TO_DATE('01.01.9000')
AND so.END_DATE = TO_DATE('01.01.9000')
AND dp.END_DATE = TO_DATE('01.01.9000');



SELECT * FROM RSA_EGARANT.POLICY_SUBJ_INFO psi JOIN CHECK_LOG cl ON psi.CHECK_LOG_ID = cl.CHECK_LOG_ID
LEFT JOIN RSA_EGARANT.CHECK_INS_DOC_STATUS_LOG ON cl.CHECK_LOG_ID = CHECK_INS_DOC_STATUS_LOG.CHECK_LOG_ID
WHERE psi.DRAFT_POLICY_ID = '53';


SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi 
JOIN RSA_EGARANT.SUBJECT_OSAGO so ON pi.PERSONAL_INFO_ID = so.PERSONAL_INFO_ID
JOIN RSA_EGARANT.SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
JOIN RSA_EGARANT.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
JOIN RSA_EGARANT.DRAFT_POLICY dp ON psi.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
----------------------
/*JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj ON dp.INS_COMP_DRAFT_POLICY_ID = ppj.INS_COMP_DRAFT_POLICY_ID
JOIN RSA_EOSAGO.EPOLICY e ON ppj.POLICY_PROC_ID = e.POLICY_PROC_ID*/
----------------------
--WHERE dp.DRAFT_POLICY_ID = '110'
where dp.APPLICATION_ID = '145326109'
--WHERE pi.PERSONAL_INFO_ID = '159'
AND psi.END_DATE = TO_DATE('01.01.9000')
AND so.END_DATE = TO_DATE('01.01.9000')
AND dp.END_DATE = TO_DATE('01.01.9000');