SELECT * FROM MP_REQUEST_JOURNAL mrj ORDER by mrj.BEG_DATE desc;

SELECT * FROM REQUEST_TYPE rt ORDER by rt.REQUEST_TYPE_ID;

SELECT * FROM CK_REQUEST_JOURNAL crj ORDER by crj.BEG_DATE DESC;

SELECT * FROM CK c;

SELECT * FROM DKBM_REQUEST_JOURNAL drj ORDER BY drj.SYS_CORR_DATE DESC;

SELECT * FROM NSI_SERVICE_METHOD nsm ORDER by nsm.ID;

SELECT * FROM REQUEST_STATUS rs ORDER by rs.REQUEST_STATUS_ID;

SELECT
  COUNT(mrj.REQ_ID) "Кол-во",
  TO_CHAR(mrj.BEG_DATE,'mm.yyyy') "месяц.год",
  rt.REQUEST_TYPE "Тип запроса"
  FROM MP_REQUEST_JOURNAL mrj
  JOIN REQUEST_TYPE rt ON mrj.REQ_TYPE_ID = rt.REQUEST_TYPE_ID
  WHERE mrj.BEG_DATE >= TRUNC(SYSDATE,'yyyy')
  GROUP BY 
  TO_CHAR(mrj.BEG_DATE,'mm.yyyy'),
  rt.REQUEST_TYPE
  ORDER BY
  TO_CHAR(mrj.BEG_DATE,'mm.yyyy'),
  rt.REQUEST_TYPE;

SELECT 
COUNT(crj.REQ_ID) "Кол-во",
TO_CHAR(crj.BEG_DATE,'mm.yyyy') "месяц.год" 
FROM CK_REQUEST_JOURNAL crj WHERE crj.BEG_DATE >= TRUNC(SYSDATE,'yyyy')
GROUP BY 
TO_CHAR(crj.BEG_DATE,'mm.yyyy')
ORDER by 
TO_CHAR(crj.BEG_DATE,'mm.yyyy');