SELECT * FROM RSA_EOSAGO.INS_COMPANY ic WHERE ic.INS_COMPANY LIKE '%Страховая%';

--213	АО  "Страховая бизнес группа"	17000000

SELECT * FROM RSA_EOSAGO.REQUEST_TYPE rt ORDER by rt.REQ_TYPE_ID;

--36	Запрос на загрузку проекта договора е-ОСАГО
--37	Запрос на изменение статуса проекта договора е-ОСАГО

SELECT
  ic.INS_COMPANY,
  ppj.INS_COMP_DRAFT_POLICY_ID,
  ppj.POLICY_SERIAL,
  ppj.policy_number,
  ppj.REQ_STATUS_ID,
  ppj.PROC_QUEUE_DATE,
  XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('UTF-8')) AS XML
  FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
  JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj ON irj.INS_REQ_JOUR_ID = ppj.INS_REQ_JOUR_ID
  JOIN RSA_EOSAGO.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE ppj.PROC_QUEUE_DATE BETWEEN TO_DATE ('21.05.18') AND TO_DATE ('28.05.18')
  AND irj.REQ_TYPE_ID = (36)
  AND irj.INS_COMPANY_ID = 213
  ORDER by ppj.PROC_QUEUE_DATE;

SELECT
  ic.INS_COMPANY,
  cpsj.INS_COMP_DRAFT_POLICY_ID,
  cpsj.POLICY_SERIAL,
  cpsj.POLICY_NUMBER,
  cpsj.REQ_STATUS_ID,
  cpsj.PROC_QUEUE_DATE,
  XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('UTF-8')) AS XML
  FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
  JOIN RSA_EOSAGO.CHANGE_POLICY_STATUS_JOUR cpsj ON irj.INS_REQ_JOUR_ID = cpsj.INS_REQ_JOUR_ID
  JOIN RSA_EOSAGO.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE cpsj.PROC_QUEUE_DATE BETWEEN TO_DATE ('21.05.18') AND TO_DATE ('28.05.18')
  AND irj.REQ_TYPE_ID = (37)
  AND irj.INS_COMPANY_ID = 213
  ORDER by cpsj.PROC_QUEUE_DATE;

SELECT 
  * 
  FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj 
  WHERE ppj.PROC_QUEUE_DATE BETWEEN TO_DATE ('21.05.18') AND TO_DATE ('28.05.18')
  AND ppj.INS_COMPANY_ID = 213;