SELECT * FROM rsa_egarant.NSI_DIRECTORY_MOD_MODEL ndmm WHERE ndmm.RELEVANCE = 1;
select * from rsa_egarant.kladr k;
SELECT * FROM RSA_EGARANT.NSI_KOEF_KM nkk;
SELECT * FROM RSA_EGARANT.NSI_KOEF_KN nkk;
SELECT * FROM RSA_EGARANT.NSI_KOEF_KO nkk;
SELECT * FROM RSA_EGARANT.NSI_KOEF_KP nkk;
SELECT * FROM RSA_EGARANT.NSI_KOEF_KS nkk;
SELECT * FROM RSA_EGARANT.NSI_KOEF_KVS nkk;
SELECT * FROM RSA_EGARANT.NSI_KT nk;
SELECT * FROM RSA_EGARANT.NSI_TARIFF_BASE ntb;

SELECT * FROM RSA_EGARANT.DRAFT_POLICY dp WHERE dp.DRAFT_POLICY_ID = '69';
--------------
SELECT * FROM RSA_EGARANT.NSI_VEHICLE_CATEGORY nvc;
--------------
SELECT SYSDATE - 1500 FROM DUAL;
SELECT ADD_MONTHS(SYSDATE,12) FROM DUAL;
SELECT * FROM DRAFT_POLICY dp WHERE application_id = '145409046';
select * from rsa_egarant.kladr k WHERE NAME LIKE '%Москва%';
SELECT * FROM RSA_EGARANT.NSI_DIRECTORY_MOD_MODEL ndmm 
JOIN RSA_EGARANT.NSI_MODEL ON ndmm.MODEL_ID = NSI_MODEL.MODEL_ID
JOIN RSA_EGARANT.NSI_BRAND nb ON NSI_MODEL.BRAND_ID = nb.BRAND_ID
WHERE ndmm.MOD_MODEL_ID = '261010422';

SELECT * FROM RSA_EGARANT.CALCULATED_INS_PREMIUM cip;

SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi;
SELECT * FROM RSA_EGARANT.POLICY_SUBJ_INFO psi WHERE psi.END_DATE = TO_DATE('01.01.9000');

SELECT * FROM RSA_EGARANT.INS_COMPANY ic JOIN "USER" u ON ic.INS_COMPANY_ID = u.INS_COMPANY_ID WHERE ic.INS_COMPANY_ID = 10;
 
 
 SELECT * /*
pi.FIRST_NAME,
pi.MIDDLE_NAMES,
pi.LAST_NAME,
pi.BIRTH_DATE,
pi.HASH,
sd.DOC_TYPE_ID,
dt.DOC_TYPE,
sd.DOC_SERIAL_ORIGIN,
sd.DOC_NUMBER_ORIGIN,
CASE 
WHEN psi.IS_POLICY_OWNER = 1 THEN 'Страхователь'
ELSE NULL
END AS IS_POLICY_OWNER,
case
WHEN psi.IS_DRIVER = 1 THEN 'Водитель'
else NULL
end as IS_DRIVER,
case
WHEN psi.IS_CAR_OWNER = 1 THEN 'Собственник'
else null
end as IS_CAR_OWNER,
--psi.IS_POLICY_OWNER,
--psi.IS_DRIVER,
--psi.IS_CAR_OWNER,
psi.CATEGORY_DRIVER_DOC,
psi.DRV_FRST_DATE,
dp.KBM_CALC,
dp.TRAILER_KPR,
dp.IS_RENT,
dp.USE_TC_ID,
dp.IS_TRANS_CAR,
dp.POLICY_CREATE_DATE,
dp.POLICY_BEG_DATE,
dp.POLICY_END_DATE,
dp.APPLICATION_ID,
dp.POLICY_SERIAL,
dp.POLICY_NUMBER,
v.LICENSE_PLATE_ORIGIN,
v.VIN_ORIGIN,
v.BODY_NUMBER_ORIGIN,
v.CHASSIS_NUMBER_ORIGIN,
vni.VEH_CATEGORY,
vni.YEAR_ISSUE,
vni.ENGINE_POWER,
vni.MAX_WEIGHT,
vni.VEH_DOC_SERIAL_ORIGIN,
vni.VEH_DOC_NUMBER_ORIGIN,
ndmm.VEHICLE_CATEGORY_ID,
ndmm.VEHICLE_TYPE_ID,
ndmm.MOD_MODEL_ID,
NAME,
nb.BRAND_NAME*/
FROM RSA_EGARANT.PERSONAL_INFO pi 
JOIN RSA_EGARANT.SUBJECT_OSAGO so ON pi.PERSONAL_INFO_ID = so.PERSONAL_INFO_ID
LEFT JOIN RSA_EGARANT.SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
LEFT JOIN RSA_EGARANT.DOC_TYPE dt ON sd.DOC_TYPE_ID = dt.DOC_TYPE_ID
JOIN RSA_EGARANT.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
JOIN RSA_EGARANT.DRAFT_POLICY dp ON psi.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
----------------------
--JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj ON dp.INS_COMP_DRAFT_POLICY_ID = ppj.INS_COMP_DRAFT_POLICY_ID
--JOIN RSA_EOSAGO.EPOLICY e ON ppj.POLICY_PROC_ID = e.POLICY_PROC_ID
----------------------
join RSA_EGARANT.VEHICLE v ON psi.VEHICLE_REC_ID = v.VEHICLE_REC_ID
JOIN RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni ON dp.VEHICLE_NON_IDENTIFYING_REC_ID = vni.VEHICLE_NON_IDENTIFYING_REC_ID
JOIN RSA_EGARANT.NSI_DIRECTORY_MOD_MODEL ndmm ON vni.MARK_MODEL_ID = ndmm.MOD_MODEL_ID
JOIN RSA_EGARANT.NSI_MODEL ON ndmm.MODEL_ID = NSI_MODEL.MODEL_ID
JOIN RSA_EGARANT.NSI_BRAND nb ON NSI_MODEL.BRAND_ID = nb.BRAND_ID
----------------------
--WHERE dp.DRAFT_POLICY_ID = '230'
WHERE application_id = '119528781'
AND psi.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND so.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND dp.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss');




SELECT c.*, f.formula_text
  FROM calculated_ins_premium c
  JOIN ins_prem_calc_formula f
    ON f.ins_prem_calc_formula_id = c.ins_prem_calc_formula_id
 WHERE c.calculated_ins_premium_id in (3,2);

SELECT *
    FROM nsi_directory_mod_model d
    JOIN NSI_VEHICLE_CATEGORY v
    ON v.VEHICLE_CATEGORY_ID=d.VEHICLE_CATEGORY_ID
    JOIN nsi_model m
      ON m.model_id = d.model_id
    JOIN nsi_brand b
      ON b.brand_id = m.brand_id   
   WHERE d.MOD_MODEL_ID in (261010422);


SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi
JOIN RSA_EGARANT.SUBJECT_OSAGO so ON pi.PERSONAL_INFO_ID = so.PERSONAL_INFO_ID
LEFT JOIN RSA_EGARANT.SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
JOIN RSA_EGARANT.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID;

SELECT * FROM RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni
JOIN RSA_EGARANT.VEHICLE v ON vni.VEHICLE_REC_ID = v.VEHICLE_REC_ID
JOIN RSA_EGARANT.NSI_DIRECTORY_MOD_MODEL ndmm ON vni.MARK_MODEL_ID = ndmm.MOD_MODEL_ID
JOIN RSA_EGARANT.NSI_MODEL ON ndmm.MODEL_ID = NSI_MODEL.MODEL_ID
JOIN RSA_EGARANT.NSI_BRAND nb ON NSI_MODEL.BRAND_ID = nb.BRAND_ID
WHERE ndmm.MOD_MODEL_ID = '125006385';

SELECT * FROM RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni
JOIN RSA_EGARANT.VEHICLE v ON vni.VEHICLE_REC_ID = v.VEHICLE_REC_ID
JOIN RSA_EGARANT.NSI_DIRECTORY_MOD_MODEL ndmm ON vni.MARK_MODEL_ID = ndmm.MOD_MODEL_ID
JOIN RSA_EGARANT.NSI_MODEL ON ndmm.MODEL_ID = NSI_MODEL.MODEL_ID
JOIN RSA_EGARANT.NSI_BRAND nb ON NSI_MODEL.BRAND_ID = nb.BRAND_ID
WHERE ndmm.MOD_MODEL_ID = '73021087';

SELECT * FROM RSA_EGARANT.CHECK_INS_DOC_STATUS_LOG cidsl;


SELECT * FROM RSA_EGARANT.PAYMENT_JOUR pj JOIN CALCULATED_INS_PREMIUM cip ON pj.CALCULATED_INS_PREMIUM_ID = cip.CALCULATED_INS_PREMIUM_ID
WHERE cip.DRAFT_POLICY_ID = '217';
SELECT * FROM ORDER_STATUS os;
SELECT * FROM RSA_EGARANT.PAID_INS_PREMIUM pip;

SELECT * FROM CALCULATED_INS_PREMIUM cip left JOIN RSA_EGARANT.PAID_INS_PREMIUM pip ON cip.CALCULATED_INS_PREMIUM_ID = pip.CALC_INS_PREMIUM_ID
WHERE cip.DRAFT_POLICY_ID = '217'; --234

SELECT * FROM RSA_EGARANT.CALCULATED_INS_PREMIUM cip left JOIN PAYMENT_JOUR pj ON cip.CALCULATED_INS_PREMIUM_ID = pj.CALCULATED_INS_PREMIUM_ID
JOIN DRAFT_POLICY dp ON cip.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
WHERE dp.DRAFT_POLICY_ID = '230';
145433061