SELECT * FROM RSA1.SUBJECT_OSAGO so JOIN RSA1.SUBJ_DOC sd ON so.SUBJ_OSAGO_DOC_REC_ID = sd.DOC_REC_ID
  JOIN RSA1.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
  WHERE so.SUBJ_HASH = 'B1BF0AB74EB55942EC372EE04196557A34DA5CF5D620EB2B4DAA9E351101E999' AND sd.DOC_NUMBER = '805695'
  ORDER BY psi.SYS_CORR_DATE DESC;


SELECT DISTINCT
  ic.INS_COMPANY "Наименование СК",
  po.BSO_NUMBER "Номер договора",
  po.POLICY_AGGR_ID "ДС",
  po.AGR_CREATE_DATE "Дата закл. ДС",
  po.INS_COMP_POLICY_ID "Идентификатор договора",
  po.POLICY_CREATE_DATE "Дата заключения",
  po.POLICY_BEG_DATE "Дата начала действия",
  po.POLICY_END_DATE "Дата окончания",
  so.SUBJ_HASH "Хеш",
  sd.DOC_FULL_NUM "Серия и номер документа"
  FROM RSA1.SUBJECT_OSAGO so JOIN RSA1.SUBJ_DOC sd ON so.SUBJ_OSAGO_DOC_REC_ID = sd.DOC_REC_ID
  JOIN RSA1.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
  JOIN RSA1.POLICY_OSAGO po ON psi.POLICY_REC_ID = po.POLICY_REC_ID
  JOIN RSA1.INS_COMPANY ic ON po.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE so.SUBJ_HASH = 'B1BF0AB74EB55942EC372EE04196557A34DA5CF5D620EB2B4DAA9E351101E999' AND sd.DOC_FULL_NUM = '4509805695'
  AND po.IS_TECH_COR = 0
  and po.RECALL_POLICY_UNQ_ID = 0
  AND po.RECALL_ADD_AGR_REC_ID = 0
  ORDER by po.POLICY_CREATE_DATE;
