SELECT * FROM RSA_EOSAGO.INS_COMPANY ic
LEFT JOIN RSA_EOSAGO."USER" u ON ic.INS_COMPANY_ID = u.INS_COMPANY_ID
--WHERE ic.STOP_LIST_TYPE_ID  !='4'
--WHERE ic.INSURER_ID IN ('14800000')
where ic.INS_COMPANY_ID = '222'
;

SELECT * FROM RSA_EOSAGO.NSI_STOP_LIST_TYPE "nslt";

SELECT * FROM RSA_EOSAGO.POLICY_NUMBERS pn 
JOIN RSA_EOSAGO.POLICY_NUMBERS_COUNT pnc ON pn.POLICY_NUMBERS_ID = pnc.POLICY_NUMBERS_ID
WHERE pn.INS_COMPANY_ID = '271';
SELECT * FROM RSA_EOSAGO.EPOLICY e 
--LEFT JOIN PRINCIPAL_EPOLICY pe ON e.POLICY_REC_ID = pe.POLICY_REC_ID
WHERE e.POLICY_NUMBER = '0101100717' AND e.IS_TECH_COR = 0;

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.INS_COMP_DRAFT_POLICY_ID LIKE '%2798473657%';

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.INS_COMP_DRAFT_POLICY_ID = 'RSA_1786433531_19112018115506000' AND e.IS_TECH_COR = 0 AND e.RECALL_POLICY_UNQ_ID = 0 AND e.RECALL_ADD_AGR_REC_ID = 0 AND e.POLICY_STATE_ID = 1 AND e.POLICY_AGGR_ID = '0';
SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_AGGR_ID = '20170320162001';
SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj 
LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_DKBM_ERR ppde ON ppj.POLICY_PROC_ID = ppde.POLICY_PROC_ID
WHERE ppj.INS_COMP_DRAFT_POLICY_ID IN (SELECT e.INS_COMP_DRAFT_POLICY_ID FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_NUMBER = '0097198145')
--AND ppj.INS_COMPANY_ID = '2420092325455
order by ppj.PROC_QUEUE_DATE;
SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
--WHERE ppj.INS_COMP_DRAFT_POLICY_ID = '975043028'
--WHERE ppj.POLICY_NUMBER = '0002809893'
--AND ppj.INS_COMPANY_ID = '267'
WHERE ppj.TRIP_NUM = 'PE_1760k00000000748_003'
--WHERE ppj.INS_REQ_JOUR_ID = '1509623939'
--where ppj.INS_COMP_DRAFT_POLICY_ID LIKE  '%776421577%'
--ppj.REQ_STATUS_ID = 3 AND ppj.HANDLE_TYPE_ID = '0' AND ppj.PROC_BEG_DATE >= TRUNC(SYSDATE)
order by ppj.PROC_QUEUE_DATE;
SELECT * FROM RSA_EOSAGO.CHANGE_POLICY_STATUS_JOUR cpsj LEFT JOIN RSA_EOSAGO.CHANGE_POLICY_STATUS_ERR cpse ON cpsj.CHANGE_POLICY_STATUS_JOUR_ID = cpse.CHANGE_POLICY_STATUS_JOUR_ID
  LEFT JOIN RSA_EOSAGO.CHANGE_POLICY_STATUS_DKBM_ERR cpsde ON cpsj.CHANGE_POLICY_STATUS_JOUR_ID = cpsde.CHANGE_POLICY_STATUS_JOUR_ID
WHERE cpsj.INS_COMP_DRAFT_POLICY_ID IN (SELECT e.INS_COMP_DRAFT_POLICY_ID FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_NUMBER = '0101584758')
--AND cpsj.INS_COMPANY_ID = '26'
order by cpsj.PROC_QUEUE_DATE;

ХХХ

SELECT 
cpsj.INS_REQ_JOUR_ID,
cpsj.INS_COMP_DRAFT_POLICY_ID,
cpsj.policy_serial,
cpsj.POLICY_NUMBER,
cpsj.REQ_STATUS_ID,
cpsj.CHANGE_DATE,
cpsj.TRIP_DATE,
cpsj.TRIP_NUM
FROM RSA_EOSAGO.CHANGE_POLICY_STATUS_JOUR cpsj LEFT JOIN RSA_EOSAGO.CHANGE_POLICY_STATUS_ERR cpse ON cpsj.CHANGE_POLICY_STATUS_JOUR_ID = cpse.CHANGE_POLICY_STATUS_JOUR_ID
WHERE cpsj.TRIP_NUM = 'PE_1760k00000000748_003'
--AND cpsj.INS_COMPANY_ID = '267'
--where cpsj.POLICY_NUMBER in ('0004097957', '0004052216', '0004114379', '0003771647', '0004074532') AND cpsj.REQ_STATUS_ID = '3'
--where cpsj.INS_REQ_JOUR_ID = '1062733404'
--WHERE cpsj.INS_COMP_DRAFT_POLICY_ID like '%776421577%'
--where cpsj.REQ_STATUS_ID = 3 AND TRUNC(cpsj.PROC_END_DATE) = TRUNC(SYSDATE) AND cpsj.INS_COMPANY_ID = '12'
order by cpsj.PROC_QUEUE_DATE;

SELECT * FROM rsa_eosago.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '459263272';

SELECT * FROM RSA_EOSAGO.SUBJECT_OSAGO so JOIN RSA_EOSAGO.SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
WHERE so.SUBJ_HASH = '5C2505B5CE1992A1BCC0CA6D97EDADAE2A69A41C1A88E24B79D10EC4FB9591AF';

SELECT * FROM RSA_EOSAGO.CHECK_OWNER_REQUEST_JOUR corj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON corj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID = '481245736';

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = '197';
SELECT COUNT(*),req_type_id --req_status_id
FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj /*WHERE irj.INS_COMPANY_ID = '269' AND irj.REQ_TYPE_ID in ('36')*/ ORDER BY irj.INS_REQ_JOUR_ID DESC) --WHERE ROWNUM < 1000
where beg_date >= TO_DATE ('23.08.2017 23:00:00','dd.mm.yyyy hh24:mi:ss') --AND REQ_STATUS_id NOT IN ('6')
--ORDER by END_DATE DESC
AND req_type_id = '2'
group BY req_type_id
;

SELECT * FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE /*irj.INS_COMPANY_ID = '257' AND*/ irj.REQ_TYPE_ID in ('14') ORDER BY irj.INS_REQ_JOUR_ID DESC) WHERE ROWNUM < 1000
and beg_date >= TO_DATE ('28.11.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') 
and beg_date <= TO_DATE ('28.11.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
--AND REQ_STATUS_id IN ('603')
ORDER by END_DATE DESC;

SELECT * FROM RSA_EOSAGO.POLICY_STATE ps ORDER by ps.POLICY_STATE_ID;

SELECT 
COUNT (*),qcm.REGION
FROM RSA_EOSAGO.QUEUE_CHANNEL_MESSAGE qcm GROUP BY qcm.REGION;

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID = '74349211';

select ic.ins_company_id,ic.company_short_name,
  (select sum(pn.all_numbers) from policy_numbers pn
    where pn.ins_company_id = ic.ins_company_id
     --and pn.date_beg <= to_date('01.02.2017')
  --AND pn.DATE_BEG BETWEEN TO_DATE ('01.02.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('22.02.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
  ) "Зарезирвировано",
  (SELECT COUNT(1) FROM EPOLICY e
    WHERE e.INS_COMPANY_ID = ic.INS_COMPANY_ID
    AND e.POLICY_STATE_ID IN(1,2)
     --AND e.POLICY_CREATE_DATE <= to_date('22.02.2017')
  --AND e.POLICY_CREATE_DATE BETWEEN TO_DATE ('01.02.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('22.02.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
  ) "Использовано" ,
  (
  (select sum(pn.all_numbers) from policy_numbers pn
    where pn.ins_company_id = ic.ins_company_id) - 
    (SELECT COUNT(1) FROM EPOLICY e
    WHERE e.INS_COMPANY_ID = ic.INS_COMPANY_ID
    AND e.POLICY_STATE_ID IN(1,2))
  ) "Остатки"
  from INS_COMPANY_EXTRA_INFO ic --WHERE ic.INS_COMPANY_ID = '225'
    order by ic.company_short_name;

SELECT irj.INS_REQ_JOUR_ID "ID запроса от СК",
ic.INS_COMPANY "Наименование СК",
irj.INS_COMPANY_ID "ID СК",
rt.REQ_TYPE "Тип запроса",
rs.REQ_STATUS "Статус обработки запроса",
irj.BEG_DATE "Дата получения запроса",
irj.END_DATE "Дата ответа на запрос",
irj.REQ_STATUS_MESSAGE "Описание ошибки"
FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
JOIN RSA_EOSAGO.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON irj.REQ_TYPE_ID = rt.REQ_TYPE_ID
JOIN RSA_EOSAGO.REQUEST_STATUS rs ON irj.REQ_STATUS_ID = rs.REQ_STATUS_ID
WHERE irj.INS_REQ_JOUR_ID IN  ('2429168935');

SELECT
irj.INS_REQ_JOUR_ID "ID запроса от СК",
corj.SUBJ_HASH "Хеш субъекта",
dt.DOC_TYPE "Тип документа",
corj.DOC_SERIAL "Cерия",
corj.DOC_NUMBER "Номер",
corj.ADDRESS_RSA_CODE "Код справочника РСА-КЛАДР",
corj.COUNTRY_CODE "КОД страны в ОКСМ",
crj.DATE_REQUEST "Дата запроса от СК",
crj.PROC_BEG_DATE "Дата начала обработки",
crj.PROC_END_DATE "Дата окончания обработки",
crj.IS_FOUND "Найден",
crj.IS_CHECKED "Проверку прошел",
crj.FAILED_TEST_FILELDS "Причина не прохождения"
FROM RSA_EOSAGO.CHECK_OWNER_REQUEST_JOUR corj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON corj.CHECK_REQ_ID = crj.CHECK_REQ_ID
JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON crj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
JOIN RSA_EOSAGO.DOC_TYPE dt ON corj.DOC_TYPE_ID = dt.DOC_TYPE_ID
WHERE crj.INS_REQ_JOUR_ID IN ('2429168935');

SELECT 
irj.INS_REQ_JOUR_ID "ID запроса от СК",
cdrj.SUBJ_HASH "Хеш субъекта",
cdrj.DRIVER_DOC_SERIAL "Cерия",
cdrj.DRIVER_DOC_NUMBER "Номер",
cdrj.DRIVER_DOC_DATE "Дата выдачи первого ВУ",
cdrj.CATEGORY_DRIVER_DOC "Категория ТС",
crj.DATE_REQUEST "Дата запроса на проверку",
crj.IS_FOUND "Найден",
crj.IS_CHECKED "Проверку прошел",
crj.FAILED_TEST_FILELDS "Причина не прохождения"
FROM RSA_EOSAGO.CHECK_DRIVER_REQUEST_JOUR cdrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cdrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON crj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
WHERE crj.INS_REQ_JOUR_ID in ('2422428472');

SELECT
irj.INS_REQ_JOUR_ID "ID запроса от СК",
VIN,
cvrj.YEAR_ISSUE "Год выпуска",
cvrj.VEH_CATEGORY "Категория ТС",
dt.DOC_TYPE "Тип документа ТС",
cvrj.VEH_DOC_SERIAL "Серия",
cvrj.VEH_DOC_NUMBER "Номер",
cvrj.MODEL_CODE "Код марки",
cvrj.ENGINE_POWER "Мощность",
crj.DATE_REQUEST "Дата запроса на проверку",
--crj.INS_REQ_JOUR_ID "ID запроса от СК",
crj.IS_FOUND "Найден",
crj.IS_CHECKED "Проверку прошел",
crj.FAILED_TEST_FILELDS "Причина не прохождения"
FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
JOIN RSA_EOSAGO.DOC_TYPE dt ON cvrj.DOC_TYPE_TS_ID = dt.DOC_TYPE_ID
JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON crj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
WHERE crj.INS_REQ_JOUR_ID = '2429168935';

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID = '617308004';

SELECT * FROM RSA_EOSAGO.POLICY_NUMBERS pn 
JOIN RSA_EOSAGO.POLICY_NUMBERS_COUNT pnc ON pn.POLICY_NUMBERS_ID = pnc.POLICY_NUMBERS_ID
WHERE pn.INS_COMPANY_ID = '225' ORDER BY pn.DATE_BEG desc;

SELECT DISTINCT dscj.REQ_TYPE_ID FROM RSA_EOSAGO.DKBM_SENT_CHECK_JOUR dscj;
--'251977425', '253220529'

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '2575525511';

SELECT * FROM RSA_EOSAGO.QUEUE_2 q;

SELECT COUNT(*), pcm.REGION,  SYSDATE FROM RSA_EOSAGO.POLICY_CHANNEL_MESSAGE pcm GROUP BY pcm.REGION;

SELECT
*
FROM RSA_EOSAGO.REQUEST_TYPE rt ORDER BY rt.REQ_TYPE_ID;



SELECT 
*
FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_CREATE_DATE >= TO_DATE ('30.04.2017 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND e.POLICY_STATE_ID = '2' AND e.IS_TECH_COR = 0 AND e.RECALL_POLICY_UNQ_ID = 0 AND e.RECALL_ADD_AGR_REC_ID = 0;

SELECT 
*
FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_CREATE_DATE >= trunc(SYSDATE)
AND e.POLICY_STATE_ID = '2' AND e.IS_TECH_COR = 0 AND e.RECALL_POLICY_UNQ_ID = 0 AND e.RECALL_ADD_AGR_REC_ID = 0;
SELECT 
*
FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_CREATE_DATE >= TO_DATE ('02.05.2017 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND e.POLICY_STATE_ID = '1' AND e.IS_TECH_COR = 0 AND e.RECALL_POLICY_UNQ_ID = 0 AND e.RECALL_ADD_AGR_REC_ID = 0;


SELECT 
*
FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_CREATE_DATE BETWEEN TO_DATE ('29.04.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('29.04.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
AND e.POLICY_STATE_ID = '0' AND e.IS_TECH_COR = 0 AND e.RECALL_POLICY_UNQ_ID = 0 AND e.RECALL_ADD_AGR_REC_ID = 0;



SELECT 
*
/*COUNT(ppj.POLICY_NUMBER) cpn,
 ppj.REQ_STATUS_ID*/

FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj 
--LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
WHERE ppj.PROC_QUEUE_DATE >= TO_DATE ('29.04.2017 00:00:00','dd.mm.yyyy hh24:mi:ss')
--AND ppj.BEG_DATE >= TO_DATE ('29.04.2017 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND ppj.HANDLE_TYPE_ID = '0'
/*GROUP BY 
--INS_COMPANY_id,
ppj.REQ_STATUS_ID
ORDER by ppj.REQ_STATUS_ID*/
;

SELECT * FROM RSA_EOSAGO.REQUEST_STATUS rs ORDER by rs.REQ_STATUS_ID;

SELECT 
coun,
rt.req_type
FROM (
SELECT COUNT(*) coun,req_type_id
FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj ORDER BY irj.INS_REQ_JOUR_ID DESC)
where beg_date BETWEEN TO_DATE('01.06.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('01.06.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
--AND ins_company_id = '10'
group BY req_type_id
)count_request_eosago
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON count_request_eosago.req_type_id = rt.REQ_TYPE_ID
;

SELECT 
coun,
rt.req_type
FROM (
SELECT COUNT(*) coun,req_type_id
FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj ORDER BY irj.INS_REQ_JOUR_ID DESC)
where beg_date BETWEEN TO_DATE('31.05.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('31.05.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
--AND ins_company_id = '10'
group BY req_type_id
)count_request_eosago
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON count_request_eosago.req_type_id = rt.REQ_TYPE_ID
;

SELECT 
coun,
rt.REQ_TYPE,
INS_COMPANY
FROM (
SELECT COUNT(*) coun,req_type_id,ins_company_id
FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj ORDER BY irj.INS_REQ_JOUR_ID DESC)
where beg_date BETWEEN TO_DATE('02.06.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('02.06.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
AND INS_COMPANY_id = '12'
group BY req_type_id, ins_company_id
)count_request_eosago
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON count_request_eosago.req_type_id = rt.REQ_TYPE_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON count_request_eosago.ins_company_id = ic.INS_COMPANY_ID
;

SELECT 
coun,
rt.REQ_TYPE,
INS_COMPANY,
beg_date
FROM (
SELECT COUNT(*) coun,req_type_id,ins_company_id
FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj ORDER BY irj.INS_REQ_JOUR_ID DESC)
where beg_date BETWEEN TO_DATE('01.06.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('01.06.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
AND INS_COMPANY_id = '12'
group BY req_type_id, ins_company_id
)count_request_eosago
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON count_request_eosago.req_type_id = rt.REQ_TYPE_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON count_request_eosago.ins_company_id = ic.INS_COMPANY_ID
;

SELECT * FROM RSA_EOSAGO.CHANGE_POLICY_STATUS_ERR cpse ORDER BY cpse.ERROR_ID;

SELECT * FROM RSA_EOSAGO.PRINCIPAL_DETERMINE pd 
JOIN RSA_EOSAGO.INS_COMPANY ic ON pd.INS_COMPANY_ID = ic.INS_COMPANY_ID
WHERE pd.INS_COMPANY_ID = '285';

SELECT * FROM RSA_EOSAGO.PTS_DISTRIBUTION pd JOIN PRINCIPAL_DETERMINE pd1 ON pd.PRINCIPAL_DETERMINE_ID = pd1.PRINCIPAL_DETERMINE_ID
WHERE pd.PRINCIPAL_DETERMINE_ID = '3088';

select COUNT(*) CONT from CHECK_REQUEST_JOUR crj WHERE crj.PROC_QUEUE_DATE >  SYSDATE-5 AND (crj.PROC_END_DATE IS NULL OR crj.REQ_STATUS_ID = 2);

SELECT * FROM SUBJECT_OSAGO so JOIN SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
JOIN POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
WHERE so.SUBJ_HASH = '1570094B96B7C2ED6A4D27B266CF2ADBDF6825928CF66378FE2F9AC445D74AE8';

select * from CHECK_REQUEST_JOUR crj WHERE crj.PROC_QUEUE_DATE >  SYSDATE-5 AND (crj.PROC_END_DATE IS NULL OR crj.REQ_STATUS_ID = 2)
ORDER BY crj.PROC_QUEUE_DATE;

UPDATE CHECK_REQUEST_JOUR crj SET PROC_END_DATE = SYSDATE, crj.REQ_STATUS_ID = 2000004
WHERE crj.PROC_QUEUE_DATE >  SYSDATE-5 AND (crj.PROC_END_DATE IS NULL OR crj.REQ_STATUS_ID = 2)
AND crj.CHECK_REQ_ID BETWEEN 148974758 AND 149025961;

COMMIT;

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_INS_REQ_JOUR_ID = '2587517807';

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj 
WHERE ppj.REQ_STATUS_MESSAGE like '%CRIMEA_VALIDATION%' AND ppj.HANDLE_TYPE_ID = 0;

SELECT * FROM RSA_EOSAGO.EPOLICY e JOIN POLICY_SUBJ_INFO psi ON e.POLICY_REC_ID = psi.POLICY_REC_ID
JOIN SUBJECT_OSAGO so ON psi.SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj ON e.POLICY_PROC_ID = ppj.POLICY_PROC_ID
--JOIN RSA_EOSAGO.KLADR k ON psi.ADDRESS_KLADR = k.CODE
WHERE INN is not null 
AND
  e.POLICY_STATE_ID = 1
AND ppj.HANDLE_TYPE_ID = 0
AND psi.ADDRESS_KLADR LIKE '92%'
--AND ppj.PROC_END_DATE >=TO_DATE('01.07.2017')
ORDER BY ppj.PROC_END_DATE DESC;

SELECT * FROM RSA_EOSAGO.SUBJECT_OSAGO so WHERE so.INN = '0548011249';

SELECT * 
FROM RSA_EOSAGO.CHECK_OWNER_REQUEST_JOUR corj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON corj.CHECK_REQ_ID = crj.CHECK_REQ_ID
JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON crj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
JOIN RSA_EOSAGO.DOC_TYPE dt ON corj.DOC_TYPE_ID = dt.DOC_TYPE_ID
WHERE crj.INS_REQ_JOUR_ID IN ('600973357');

--SELECT * FROM RSA_EOSAGO.CHECK_REQUEST_JOUR crj WHERE crj.INS_REQ_JOUR_ID = '567721583';

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID = '776071582';

SELECT * FROM RSA_EOSAGO.CHECK_OWNER_REQUEST_JOUR corj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON corj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID in ('2428415540');

SELECT * FROM RSA_EOSAGO.CHECK_DRIVER_REQUEST_JOUR cdrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cdrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID In ('2485331096');

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '2568701366';

SELECT * FROM REQUEST_STATUS rs ORDER BY rs.REQ_STATUS_ID;

SELECT * FROM RSA_EOSAGO.EPOLICY WHERE POLICY_UNQ_ID = '23577013';


SELECT ic.INS_COMPANY,e.POLICY_NUMBER,e.POLICY_CREATE_DATE,e.POLICY_BEG_DATE,e.POLICY_END_DATE,e.POLICY_INS_REQ_JOUR_ID,e.INS_COMP_DRAFT_POLICY_ID,e.POLICY_STATE_ID FROM RSA_EOSAGO.EPOLICY e 
  JOIN INS_COMPANY ic ON e.INS_COMPANY_ID = ic.INS_COMPANY_ID
--LEFT JOIN PRINCIPAL_EPOLICY pe ON e.POLICY_REC_ID = pe.POLICY_REC_ID
WHERE e.POLICY_NUMBER IN('0009081953', '0010011194');

SELECT * FROM RSA_EOSAGO.REQUEST_TYPE rt WHERE rt.REQ_TYPE_ID = 40;

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE  e.KBM_CALC_ID = '4170583012';

SELECT * FROM RSA_EOSAGO.DKBM_SENT_POLICY_JOUR dspj WHERE dspj.INS_REQ_JOUR_ID = '2587517807';

SELECT * FROM RSA_EOSAGO.REQUEST_STATUS rs WHERE rs.REQ_STATUS_ID = '411';

SELECT * FROM RSA_EOSAGO.NSI_STOP_LIST_TYPE nslt ORDER BY nslt.STOP_LIST_TYPE_ID;

--1199 - Другая ошибка (java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;)

SELECT
*
FROM RSA_EOSAGO.CHANGE_POLICY_STATUS_JOUR cpsj
WHERE cpsj.REQ_STATUS_MESSAGE = '1199 - Другая ошибка (java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;)'
ORDER BY cpsj.PROC_QUEUE_DATE;

SELECT * FROM RSA_EOSAGO.REQUEST_TYPE rt ORDER by rt.REQ_TYPE_ID;

SELECT
ic.INS_COMPANY,
ic.INSURER_ID,
nslt.STOP_LIST_TYPE_NAME
FROM RSA_EOSAGO.INS_COMPANY ic
JOIN RSA_EOSAGO.NSI_STOP_LIST_TYPE nslt ON ic.STOP_LIST_TYPE_ID = nslt.STOP_LIST_TYPE_ID
ORDER by ic.INSURER_ID;

SELECT
CRJ.INS_REQ_JOUR_ID,
CRJ.PROC_END_DATE - CRJ.PROC_QUEUE_DATE
FROM RSA_EOSAGO.CHECK_REQUEST_JOUR crj
WHERE CRJ.INS_REQ_JOUR_ID in (
'2696711003',
'2696712262',
'2696712262',
'2696711410',
'2696711418'
);

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE IRJ.BEG_DATE >= TRUNC(sysdate);

SELECT
*
FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
WHERE IRJ.INS_COMPANY_ID = 285
AND IRJ.REQ_TYPE_ID IN (72)
AND IRJ.BEG_DATE BETWEEN TO_DATE('08.10.2019','dd.mm.yyyy') AND TO_DATE('09.10.2019','dd.mm.yyyy') ORDER BY IRJ.BEG_DATE;

SELECT
*
FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
WHERE IRJ.INS_COMPANY_ID = 285
AND IRJ.REQ_TYPE_ID IN (70)
AND IRJ.BEG_DATE BETWEEN TO_DATE('08.10.2019','dd.mm.yyyy') AND TO_DATE('09.10.2019','dd.mm.yyyy') ORDER BY IRJ.BEG_DATE;