SELECT * FROM INS_COMPANY ic WHERE ic.INS_COMPANY_ID = '10';
SELECT * FROM INS_COMPANY ic WHERE ic.INSURER_ID = '08100000';


SELECT * FROM PRINCIPAL_DETERMINE pd JOIN INS_COMPANY ic ON pd.INS_COMPANY_ID = ic.INS_COMPANY_ID WHERE pd.INS_COMPANY_ID = 228;


SELECT ic.INS_COMPANY,
         pd1.CALCULATION_DATE,
         pd.PTS_NUMBER 
    FROM PTS_DISTRIBUTION pd 
    JOIN PRINCIPAL_DETERMINE pd1 ON pd.PRINCIPAL_DETERMINE_ID = pd1.PRINCIPAL_DETERMINE_ID
    JOIN INS_COMPANY ic ON pd1.INS_COMPANY_ID = ic.INS_COMPANY_ID
    WHERE pd1.PRINCIPAL_DETERMINE_ID = 2344
    AND pd.PTS_NUMBER NOT IN
    (
    SELECT     pd.PTS_NUMBER 
    FROM PTS_DISTRIBUTION pd 
    JOIN PRINCIPAL_DETERMINE pd1 ON pd.PRINCIPAL_DETERMINE_ID = pd1.PRINCIPAL_DETERMINE_ID
    JOIN INS_COMPANY ic ON pd1.INS_COMPANY_ID = ic.INS_COMPANY_ID
    WHERE pd1.PRINCIPAL_DETERMINE_ID = 2344
    AND pd.PTS_NUMBER BETWEEN '002000' AND '003000'
    );



SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj WHERE ppj.TRIP_NUM like '%pmieg%';

SELECT * FROM RSA_EOSAGO.PTS_DISTRIBUTION_LIST pdl WHERE ROWNUM< 2;


SELECT * FROM RSA_EOSAGO.SETTINGS s;




SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.INS_COMP_DRAFT_POLICY_ID = 'pmiegDismasApp02';

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
WHERE ppj.INS_COMP_DRAFT_POLICY_ID IN (SELECT e.INS_COMP_DRAFT_POLICY_ID FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_NUMBER = '0000821638')
--AND ppj.INS_COMPANY_ID = '251'
order by ppj.PROC_QUEUE_DATE;


SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '145433061';

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID = '144811439';

SELECT * FROM RSA_EOSAGO.VEHICLE v WHERE v.VIN = '32112332145652134';

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj
LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
--WHERE ppj.INS_REQ_JOUR_ID = '145326109';
WHERE ppj.INS_COMP_DRAFT_POLICY_ID = 'RSA_145433061_20072017173339000';

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_INS_REQ_JOUR_ID = '145433061';

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.INS_COMP_DRAFT_POLICY_ID = 'RSA_145426646_20072017113937000';

SELECT * FROM RSA_EOSAGO.CHANGE_POLICY_STATUS_JOUR cpsj WHERE cpsj.INS_COMP_DRAFT_POLICY_ID = 'RSA_145426646_20072017113937000';