SELECT * FROM RSA_eosago.INS_COMPANY ic 
JOIN "USER" u ON ic.INS_COMPANY_ID = u.INS_COMPANY_ID
WHERE ic.ins_company_id = '269';
--WHERE ic.INSURER_ID = '08400000';
/*update settings x set x.int_value = 30 where x.code='SHARE_PERCENT';
COMMIT;*/
--update PRINCIPAL_DETERMINE set PTS_DISTRIBUTION_DATE = to_date ('28.06.2017', 'dd.mm.yyyy'), CALCULATION_DATE= to_date (''28.06.2017', 'dd.mm.yyyy') where STATUS=1;

SELECT * FROM RSA_EOSAGO.PRINCIPAL_DETERMINE pd WHERE pd.CALCULATION_DATE >= to_date ('28.06.2017', 'dd.mm.yyyy') and STATUS=1;
SELECT * FROM RSA_EOSAGO.PRINCIPAL_DETERMINE pd WHERE STATUS=0;
SELECT * FROM RSA_EOSAGO. PTS_DISTRIBUTION_HISTORY pdh WHERE pdh.PRINCIPAL_DETERMINE_ID = '2296';
SELECT * FROM RSA_EOSAGO.PTS_DISTRIBUTION pd WHERE pd.PRINCIPAL_DETERMINE_ID = '2296';


SELECT * FROM RSA_EOSAGO.PRINCIPAL_DETERMINE pd JOIN INS_COMPANY ic ON pd.INS_COMPANY_ID = ic.INS_COMPANY_ID WHERE STATUS=0;


SELECT * FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = '206' AND irj.REQ_TYPE_ID in ('36') ORDER BY irj.INS_REQ_JOUR_ID DESC) WHERE ROWNUM < 1000
--where beg_date >= TO_DATE ('11.05.2017 23:15:00','dd.mm.yyyy hh24:mi:ss') --AND REQ_STATUS_id NOT IN ('6')
ORDER by END_DATE DESC;

-----------------------------------
/*DECLARE
                                    res VARCHAR2(100);
                                BEGIN
                                    res := pkg$pts.distribution_ranges;
                                END;
-----------------------------------

/*update RSA_EOSAGO.PRINCIPAL_DETERMINE pd set PTS_DISTRIBUTION_DATE = to_date ('28.06.2017', 'dd.mm.yyyy'), CALCULATION_DATE= to_date ('28.06.2017', 'dd.mm.yyyy') 
where STATUS=1 AND pd.CALCULATION_DATE = to_date ('28.06.2017', 'dd.mm.yyyy');
ROLLBACK;
COMMIT;*/


SELECT * FROM RSA_EOSAGO.REQUEST_TYPE rt ORDER by rt.REQ_TYPE_ID;

SELECT * FROM RSA_EOSAGO.CHECK_LOG;


SELECT * FROM ( SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = '285'/* AND irj.REQ_TYPE_ID in ('74')*/ ORDER BY irj.INS_REQ_JOUR_ID DESC) WHERE ROWNUM < 1000
--where beg_date >= TO_DATE ('11.05.2017 23:15:00','dd.mm.yyyy hh24:mi:ss') --AND REQ_STATUS_id NOT IN ('6')
ORDER by END_DATE DESC;

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.IS_EGARANT = '1' AND e.INS_COMPANY_ID = '269';

70	Получ. списка проектов полиса с докум-тами, треб. подтвержд.
71	Получение документов требующих подтверждения
72	Отправка подтверждения проверок док-ов проектов полиса
73	Запрос на получение списка договоров е-ОСАГО, заключенных в Модуле «Гарантия е-ОСАГО» от имени СК
74	запрос на получение данных действующих договоров е-ОСАГО, заключенных в Модуле «Гарантия е-ОСАГО» от имени СК

SELECT
DISTINCT ic.INS_COMPANY,
TO_CHAR(tt1.beg_date, 'rrrr.mm.dd') DD
/*ic.INS_COMPANY,
ic.INS_COMPANY_ID,
tt1.REQ_TYPE_ID,
rt.req_type,
COUNT(*) AS CR*/
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date >= TO_DATE ('04.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss')
/*group by
ic.INS_COMPANY,
ic.INS_COMPANY_ID,
tt1.REQ_TYPE_ID,
rt.req_type
ORDER BY
ic.INS_COMPANY,
ic.INS_COMPANY_ID,
tt1.REQ_TYPE_ID,
rt.req_type*/
;

SELECT * FROM RSA_EOSAGO. INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '2658525';



SELECT
DISTINCT ic.INS_COMPANY,
TO_CHAR(tt1.beg_date, 'rrrr.mm.dd')
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date >= TO_DATE ('03.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND ic.INS_COMPANY NOT IN
(SELECT
ic.INS_COMPANY
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date >= TO_DATE ('05.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss'));

SELECT
DISTINCT ic.INS_COMPANY,
TO_CHAR(tt1.beg_date, 'rrrr.mm.dd')
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date BETWEEN TO_DATE ('03.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE ('03.07.2017 23:59:59','dd.mm.yyyy hh24:mi:ss');

SELECT
DISTINCT ic.INS_COMPANY,
TO_CHAR(tt1.beg_date, 'rrrr.mm.dd')
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date BETWEEN TO_DATE ('06.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE ('06.07.2017 23:59:59','dd.mm.yyyy hh24:mi:ss');

SELECT
DISTINCT ic.INS_COMPANY,
TO_CHAR(tt1.beg_date, 'rrrr.mm.dd')
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date BETWEEN TO_DATE ('05.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE ('05.07.2017 23:59:59','dd.mm.yyyy hh24:mi:ss');

SELECT
DISTINCT ic.INS_COMPANY,
TO_CHAR(tt1.beg_date, 'rrrr.mm.dd')
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74') 
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date BETWEEN TO_DATE ('06.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE ('06.07.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')
AND ic.INS_COMPANY NOT IN
(
SELECT
DISTINCT ic.INS_COMPANY
FROM
(SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj 
 WHERE irj.REQ_TYPE_ID in ('70','71','72','73','74')
 ORDER BY irj.INS_REQ_JOUR_ID DESC) tt1
JOIN RSA_EOSAGO.INS_COMPANY ic ON ic.INS_COMPANY_ID = tt1.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON tt1.REQ_TYPE_ID = rt.REQ_TYPE_ID
WHERE beg_date BETWEEN TO_DATE ('03.07.2017 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE ('05.07.2017 23:59:59','dd.mm.yyyy hh24:mi:ss')  
);

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
WHERE ppj.INS_COMP_DRAFT_POLICY_ID IN (SELECT e.INS_COMP_DRAFT_POLICY_ID FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_NUMBER = '0006840622')
AND ppj.INS_COMPANY_ID = '251'
order by ppj.PROC_QUEUE_DATE;

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.INS_COMP_DRAFT_POLICY_ID = 'pmiegDismasApp02';



SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '145326109';


SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
WHERE ppj.INS_COMP_DRAFT_POLICY_ID IN (SELECT e.INS_COMP_DRAFT_POLICY_ID FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_NUMBER = '0000816082')
--AND ppj.INS_COMPANY_ID = '251'
order by ppj.PROC_QUEUE_DATE;

SELECT * FROM rsa_eosago.epolicy e WHERE e.ins_comp_draft_policy_id = '92ba6fc8-734e-4805-81a5-184fc041b637';
SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj WHERE ppj.TRIP_NUM = '4e80373d-a261-4e5e-9526-cf097bc09702';
SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj WHERE ppj.INS_COMP_DRAFT_POLICY_ID = '08CF84E3-9C1B-4DF9-921A-14B7DEADBEEF';

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE e.INS_COMPANY_ID = '' AND e.IS_EGARANT = 1;