WITH BSILOSS AS (
SELECT 
INS_COMPANY_ID,
INSURER_ID,
INS_COMPANY,
INS_COMP_LOSS_ID,
REQ_STATUS_ID,
HAS_VALIDATION_ERROR,
ERROR_ID,
MESSAGE,
PROC_QUEUE_DATE,
PROC_END_DATE
FROM (
SELECT
ic.INS_COMPANY_ID,
ic.INSURER_ID,
ic.INS_COMPANY,
lpj.INS_COMP_LOSS_ID,
lpj.REQ_STATUS_ID,
lpj.HAS_VALIDATION_ERROR,
lpe.ERROR_ID,
lpe.MESSAGE,
lpj.PROC_QUEUE_DATE,
lpj.PROC_END_DATE,
MAX(lpj.LOSS_REC_ID) AS LOSS_REC_ID,
lpj.loss_proc_id
FROM BSI1.INS_COMPANY ic 
JOIN POLICY_KASKO pk ON ic.INS_COMPANY_ID = pk.INS_COMPANY_ID
join BSI1.LOSS_KASKO lk ON pk.POLICY_REC_ID = lk.POLICY_REC_ID
JOIN BSI1.LOSS_PROCESS_JOUR lpj ON lk.LOSS_REC_ID = lpj.LOSS_REC_ID
LEFT JOIN bsi1.LOSS_PROCESS_ERR lpe ON lpj.LOSS_PROC_ID = lpe.LOSS_PROC_ID
where lpj.PROC_QUEUE_DATE BETWEEN TO_DATE ('01.01.2016 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('01.04.2016 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND ic.INS_COMPANY_ID = '24'
AND pk.RECALL_POLICY_UNQ_ID = 0
AND pk.IS_TECH_COR = 0
AND lk.RECALL_LOSS_REC_ID = 0
AND lk.IS_TECH_COR = 0
AND lpj.loss_decision_id IS NULL
AND lpj.LOSS_PAYMENT_ID IS NULL
GROUP BY
ic.INS_COMPANY_ID,
ic.INSURER_ID,
ic.INS_COMPANY,
lpj.INS_COMP_LOSS_ID,
lpj.REQ_STATUS_ID,
lpj.HAS_VALIDATION_ERROR,
lpe.ERROR_ID,
lpe.MESSAGE,
lpj.LOSS_PROC_ID,
lpj.PROC_QUEUE_DATE,
lpj.PROC_END_DATE
)
),
BSIDECISIONS AS (
SELECT 
INS_COMPANY_ID,
INSURER_ID,
INS_COMPANY,
INS_COMP_LOSS_ID,
REQ_STATUS_ID,
HAS_VALIDATION_ERROR,
ERROR_ID,
MESSAGE,
PROC_QUEUE_DATE,
PROC_END_DATE
FROM (
SELECT
ic.INS_COMPANY_ID,
ic.INSURER_ID,
ic.INS_COMPANY,
lpj.INS_COMP_LOSS_ID,
lpj.REQ_STATUS_ID,
lpj.HAS_VALIDATION_ERROR,
lpe.ERROR_ID,
lpj.LOSS_REC_ID,
lpe.MESSAGE,
lpj.LOSS_PROC_ID,
lpj.PROC_QUEUE_DATE,
lpj.PROC_END_DATE,
MAX(ld.LOSS_DECISION_ID) loss_decision_id
FROM BSI1.INS_COMPANY ic 
JOIN BSI1.LOSS_DECISION ld ON ic.INS_COMPANY_ID = ld.INS_COMPANY_ID
JOIN BSI1.LOSS_PROCESS_JOUR lpj ON ld.LOSS_DECISION_ID = lpj.LOSS_DECISION_ID
LEFT JOIN LOSS_PROCESS_ERR lpe ON lpj.LOSS_PROC_ID = lpe.LOSS_PROC_ID
JOIN LOSS_KASKO lk ON ld.LOSS_REC_ID = lk.LOSS_REC_ID
where lpj.PROC_QUEUE_DATE BETWEEN TO_DATE ('01.01.2016 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('01.04.2016 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND ic.INS_COMPANY_ID = '24'
AND ld.RECALL_LOSS_REC_ID = 0
AND ld.IS_TECH_COR = 0
AND lpj.loss_decision_id IS NOT NULL
AND lpj.LOSS_PAYMENT_ID IS NULL
GROUP BY
ic.INS_COMPANY_ID,
ic.INSURER_ID,
ic.INS_COMPANY,
lpj.INS_COMP_LOSS_ID,
lpj.REQ_STATUS_ID,
lpj.HAS_VALIDATION_ERROR,
lpe.ERROR_ID,
lpj.LOSS_PROC_ID,
lpj.LOSS_REC_ID,
lpj.PROC_QUEUE_DATE,
lpj.PROC_END_DATE,
lpe.MESSAGE
)
),
BSIPAYMENTS AS (
SELECT
INS_COMPANY_ID,
INSURER_ID,
INS_COMPANY,
INS_COMP_LOSS_ID,
REQ_STATUS_ID,
HAS_VALIDATION_ERROR,
ERROR_ID,
MESSAGE,
PROC_QUEUE_DATE,
proc_end_date
from (
SELECT
ic.INS_COMPANY_ID,
ic.INSURER_ID,
ic.INS_COMPANY,
lpj.INS_COMP_LOSS_ID,
lpj.REQ_STATUS_ID,
lpj.HAS_VALIDATION_ERROR,
lpe.ERROR_ID,
lpj.LOSS_REC_ID,
lpj.LOSS_PROC_ID,
lpe.MESSAGE,
lpj.PROC_QUEUE_DATE,
lpj.proc_end_date,
MAX(lp.INS_COMP_PAY_ID) INS_COMP_PAY_ID
FROM BSI1.INS_COMPANY ic 
JOIN BSI1.LOSS_PAYMENT lp ON ic.INS_COMPANY_ID = lp.INS_COMPANY_ID
JOIN BSI1.LOSS_PROCESS_JOUR lpj ON lp.LOSS_PAYMENT_ID = lpj.LOSS_PAYMENT_ID
LEFT JOIN LOSS_PROCESS_ERR lpe ON lpj.LOSS_PROC_ID = lpe.LOSS_PROC_ID
JOIN LOSS_DECISION ld ON lp.LOSS_DECISION_ID = ld.LOSS_DECISION_ID
JOIN LOSS_KASKO lk ON ld.LOSS_REC_ID = lk.LOSS_REC_ID
where lpj.PROC_QUEUE_DATE BETWEEN TO_DATE ('01.01.2016 00:00:00','dd.mm.yyyy hh24:mi:ss') AND TO_DATE('01.04.2016 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND ic.INS_COMPANY_ID = '24'
AND lp.RECALL_LOSS_PAY_ID = 0
AND lp.IS_TECH_COR = 0
AND lpj.loss_decision_id IS NOT NULL
AND lpj.LOSS_PAYMENT_ID IS NOT  NULL
GROUP BY
ic.INS_COMPANY_ID,
ic.INSURER_ID,
ic.INS_COMPANY,
lpj.INS_COMP_LOSS_ID,
lpj.REQ_STATUS_ID,
lpj.HAS_VALIDATION_ERROR,
lpe.ERROR_ID,
lpj.LOSS_REC_ID,
lpj.LOSS_PROC_ID,
lpj.PROC_QUEUE_DATE,
lpj.proc_end_date,
lpe.MESSAGE
)
)
SELECT
INS_COMPANY_ID "ID СК В ЕАИС БСИ",
INSURER_ID "Идентификатор СК от Гос.знак",
INS_COMPANY "Наименование СК",
INS_COMP_LOSS_ID "ID убытка в СК",
REQ_STATUS_ID "Статус загрузки",
--HAS_VALIDATION_ERROR,
ERROR_ID "ID ошибки",
MESSAGE "Текст ошибки",
PROC_QUEUE_DATE "Дата постановки в очередь",
PROC_END_DATE "Дата окончания обработки"
FROM BSILOSS
UNION 
SELECT
INS_COMPANY_ID "ID СК В ЕАИС БСИ",
INSURER_ID "Идентификатор СК от Гос.знак",
INS_COMPANY "Наименование СК",
INS_COMP_LOSS_ID "ID убытка в СК",
REQ_STATUS_ID "Статус загрузки",
--HAS_VALIDATION_ERROR,
ERROR_ID "ID ошибки",
MESSAGE "Текст ошибки",
PROC_QUEUE_DATE "Дата постановки в очередь",
PROC_END_DATE "Дата окончания обработки"
FROM BSIDECISIONS
UNION 
SELECT
INS_COMPANY_ID "ID СК В ЕАИС БСИ",
INSURER_ID "Идентификатор СК от Гос.знак",
INS_COMPANY "Наименование СК",
INS_COMP_LOSS_ID "ID убытка в СК",
REQ_STATUS_ID "Статус загрузки",
--HAS_VALIDATION_ERROR,
ERROR_ID "ID ошибки",
MESSAGE "Текст ошибки",
PROC_QUEUE_DATE "Дата постановки в очередь",
PROC_END_DATE "Дата окончания обработки"
FROM BSIPAYMENTS;