SELECT
  COUNT(rrj.REPORT_REQ_JOUR_ID)rrji,ic.INS_COMPANY,sysdate
  FROM BSI1.REPORT_REQUEST_JOUR rrj
  JOIN BSI1.INS_COMPANY ic ON rrj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE rrj.SIGN_OPERATION = 1
  GROUP BY ic.INS_COMPANY;


WITH prepay AS (
SELECT
pj.PAYMENT_AMOUNT,pj.INS_COMPANY_ID 
FROM BSI1.PREPAYMENT_JOUR pj
)

SELECT
  --COUNT(rrj.REPORT_REQ_JOUR_ID) * 500 rrji,rrj.INS_COMPANY_ID,PAYMENT_AMOUNT,SYSDATE
  ic.INS_COMPANY,PAYMENT_AMOUNT - (COUNT(rrj.REPORT_REQ_JOUR_ID) * 500) resultat,SYSDATE
  FROM BSI1.REPORT_REQUEST_JOUR rrj
  JOIN prepay ON rrj.INS_COMPANY_ID = prepay.INS_COMPANY_ID
  JOIN BSI1.INS_COMPANY ic ON rrj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE rrj.SIGN_OPERATION = 1
  GROUP BY ic.INS_COMPANY,PAYMENT_AMOUNT
;
----------------------------
-- Новый актуальный скрипт
----------------------------

WITH prepay AS (
SELECT
SUM(pj.PAYMENT_AMOUNT) PAYMENT_AMOUNT,
pj.INS_COMPANY_ID 
FROM BSI1.PREPAYMENT_JOUR pj GROUP by pj.INS_COMPANY_ID
)
  SELECT
  ic.INS_COMPANY,
  p.PAYMENT_AMOUNT - (COUNT(DISTINCT rrj.REPORT_NUMBER) * 500) resultat, SYSDATE
  FROM BSI1.REPORT_REQUEST_JOUR rrj
  JOIN BSI1.INS_COMPANY ic ON rrj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  join prepay p on rrj.ins_company_id = p.ins_company_id
  WHERE rrj.SIGN_OPERATION = 1
  GROUP BY ic.INS_COMPANY,PAYMENT_AMOUNT;