SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi
WHERE UPPER(pi.LAST_NAME) = UPPER(TRIM('Дьячков')) AND UPPER(pi.FIRST_NAME) = upper(TRIM('Алексей')) AND UPPER(pi.MIDDLE_NAMES) = UPPER(TRIM('Сергеевич'));
SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi
WHERE pi.LAST_NAME = LOWER(TRIM('Кравцов')) AND pi.FIRST_NAME = LOWER(TRIM('Эдуард')) AND pi.MIDDLE_NAMES = LOWER(TRIM('Владимирович'));
SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi WHERE pi.LAST_NAME = 'Кравцов' AND pi.FIRST_NAME = 'Эдуард' AND pi.MIDDLE_NAMES = 'Владимирович';
SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi WHERE pi.LAST_NAME = TRIM('Алидибиров') AND pi.FIRST_NAME = TRIM('Алидибир') AND pi.MIDDLE_NAMES = TRIM('Курбанулаевич');

SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi WHERE pi.LAST_NAME = UPPER(TRIM('Кравцов')) OR pi.LAST_NAME = LOWER(TRIM('Эдуард'));

SELECT * FROM RSA_EGARANT.PERSONAL_INFO pi WHERE pi.LAST_NAME = 'Варин';


SELECT *
FROM RSA_EGARANT.PERSONAL_INFO pi 
JOIN RSA_EGARANT.SUBJECT_OSAGO so ON pi.PERSONAL_INFO_ID = so.PERSONAL_INFO_ID
LEFT JOIN RSA_EGARANT.SUBJ_DOC sd ON so.DOC_REC_ID = sd.DOC_REC_ID
LEFT JOIN RSA_EGARANT.DOC_TYPE dt ON sd.DOC_TYPE_ID = dt.DOC_TYPE_ID
JOIN RSA_EGARANT.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
JOIN RSA_EGARANT.DRAFT_POLICY dp ON psi.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
--where pi.personal_info_id = '5067734'
WHERE dp.APPLICATION_ID = '2544195790'--549314924
--AND (psi.IS_POLICY_OWNER = 1
--OR psi.IS_CAR_OWNER = 1)
AND psi.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND so.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
AND dp.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss');

SELECT * FROM RSA_EGARANT.DRAFT_POLICY dp 
JOIN rsa_egarant.CALCULATED_INS_PREMIUM cip ON dp.DRAFT_POLICY_ID = cip.DRAFT_POLICY_ID
LEFT JOIN rsa_egarant.PAYMENT_JOUR pj ON cip.CALCULATED_INS_PREMIUM_ID = pj.CALCULATED_INS_PREMIUM_ID
LEFT JOIN RSA_EGARANT.PAID_INS_PREMIUM pip ON cip.CALCULATED_INS_PREMIUM_ID = pip.CALC_INS_PREMIUM_ID
LEFT JOIN RSA_EGARANT.INS_PREM_CALC_FORMULA ipcf ON cip.INS_PREM_CALC_FORMULA_ID = ipcf.INS_PREM_CALC_FORMULA_ID
WHERE dp.APPLICATION_ID = '2568717496' AND dp.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss') ORDER BY pj.CREATE_DATE;

SELECT
dp.DRAFT_POLICY_ID,
dp.APPLICATION_ID,
dp.POLICY_NUMBER,
cl.CHECK_REQ_ID,
cl.IS_FOUND,
cl.IS_CHECKED,
cl.FAILED_TEST_FIELDS,
ct.TEXT,
cids.BRIEF,
cids.TEXT,
cidsl.create_date,
cidsl.CHANGE_DATE,
--cl.CHECK_LOG_ID,
--cidsl.CHECK_SCAN_EVENT_LOG_ID,
id.INSUREE_DOC_ID,
id.CHECK_INS_DOC_STATUS_LOG_ID,
id.DOC_GUID
FROM RSA_EGARANT.CHECK_INS_DOC_STATUS_LOG cidsl 
JOIN RSA_EGARANT.CHECK_INS_DOC_STATUS cids ON cidsl.CHECK_INS_DOC_STATUS_ID = cids.CHECK_INS_DOC_STATUS_ID
JOIN RSA_EGARANT.DRAFT_POLICY dp ON cidsl.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
JOIN RSA_EGARANT.CHECK_LOG cl ON cidsl.CHECK_LOG_ID = cl.CHECK_LOG_ID
JOIN RSA_EGARANT.CHECK_TYPE ct ON cl.CHECK_TYPE_ID = ct.CHECK_TYPE_ID
JOIN RSA_EGARANT.INSUREE_DOC id ON cidsl.CHECK_INS_DOC_STATUS_LOG_ID = id.CHECK_INS_DOC_STATUS_LOG_ID
WHERE dp.APPLICATION_ID = '2537398910' AND dp.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
--AND ct.TEXT LIKE 'Проверка ТС(транспортного стредства)' 
ORDER by cidsl.CREATE_DATE;
------------------------------------------------------------------------------
select * from(
SELECT 
--chids.TEXT,
ct.TEXT, cl.* FROM RSA_EGARANT.POLICY_SUBJ_INFO psi
join RSA_EGARANT.check_log cl on psi.CHECK_LOG_ID = cl.CHECK_LOG_ID 
join RSA_EGARANT.CHECK_TYPE ct on ct.CHECK_TYPE_ID = cl.CHECK_TYPE_ID
where psi.DRAFT_POLICY_ID IN 
(
SELECT DRAFT_POLICY_ID FROM RSA_EGARANT.DRAFT_POLICY dp WHERE dp.APPLICATION_ID = '2537398910'  
)
union all
SELECT distinct
--chids.TEXT,
ct.TEXT, cl.* FROM RSA_egarant.VEHICLE_NON_IDENTIFYING vni
join RSA_EGARANT.check_log cl on vni.CHECK_LOG_ID = cl.CHECK_LOG_ID 
join RSA_EGARANT.CHECK_TYPE ct on ct.CHECK_TYPE_ID = cl.CHECK_TYPE_ID
join RSA_EGARANT.DRAFT_POLICY dp on vni.VEHICLE_NON_IDENTIFYING_REC_ID=dp.VEHICLE_NON_IDENTIFYING_REC_ID
where dp.DRAFT_POLICY_ID  in 
(
SELECT DRAFT_POLICY_ID FROM RSA_EGARANT.DRAFT_POLICY dp WHERE dp.APPLICATION_ID = '2537398910'
)
UNION ALL
SELECT distinct
--chids.TEXT,
ct.TEXT, cl.* FROM RSA_EGARANT.CHECK_LOG cl 
JOIN RSA_EGARANT.VEHICLE_NON_IDENTIFYING vni ON cl.CHECK_LOG_ID = vni.TO_DIAG_CARD_CHECK_LOG_ID
join RSA_EGARANT.CHECK_TYPE ct on ct.CHECK_TYPE_ID = cl.CHECK_TYPE_ID
join RSA_EGARANT.DRAFT_POLICY dp on vni.VEHICLE_NON_IDENTIFYING_REC_ID=dp.VEHICLE_NON_IDENTIFYING_REC_ID
where dp.DRAFT_POLICY_ID  in 
(
SELECT DRAFT_POLICY_ID FROM RSA_EGARANT.DRAFT_POLICY dp WHERE dp.APPLICATION_ID = '2537398910'
)
) x 
order by x.CHECK_LOG_ID;
------------------------------------------------------------------------------
SELECT * FROM RSA_EGARANT.CHECK_SCAN_EVENT_LOG csel WHERE csel.DRAFT_POLICY_ID IN( 
SELECT DRAFT_POLICY_ID FROM RSA_EGARANT.DRAFT_POLICY dp WHERE dp.APPLICATION_ID = '2425339190'
) ORDER BY csel.CREATE_DATE;


SELECT * FROM RSA_EGARANT.CHECK_LOG cl WHERE ROWNUM > 1;

/*SELECT distinct
--chids.TEXT,
ct.TEXT, cl.* FROM RSA_EGARANT.CHECK_LOG cl 
JOIN VEHICLE_NON_IDENTIFYING vni ON cl.CHECK_LOG_ID = vni.TO_DIAG_CARD_CHECK_LOG_ID
join RSA_EGARANT.CHECK_TYPE ct on ct.CHECK_TYPE_ID = cl.CHECK_TYPE_ID
join RSA_EGARANT.DRAFT_POLICY dp on vni.VEHICLE_NON_IDENTIFYING_REC_ID=dp.VEHICLE_NON_IDENTIFYING_REC_ID
WHERE dp.APPLICATION_ID = '686719706';*/

SELECT * FROM RSA_EGARANT.CHECK_SCAN_EVENT_LOG csel WHERE TRUNC(csel.CREATE_DATE,'HH')=TRUNC(SYSDATE,'HH');

SELECT * FROM RSA_EGARANT.CHECK_SCAN_EVENT_LOG csel WHERE TRUNC(csel.CREATE_DATE)=TRUNC(SYSDATE) ORDER by csel.CREATE_DATE desc;

SELECT * FROM RSA_EGARANT.CHECK_LOG cl WHERE TRUNC(cl.CREATE_DATE)=TRUNC(sysdate) ORDER by cl.CREATE_DATE desc;

SELECT ic.INS_COMPANY FROM RSA_EGARANT.DRAFT_POLICY dp 
JOIN RSA_EGARANT.INS_COMPANY ic ON dp.INS_COMPANY_ID = ic.INS_COMPANY_ID
WHERE dp.APPLICATION_ID = '2188200023';

SELECT fpe.*,dp.APPLICATION_ID FROM RSA_EGARANT.FRAUD_POLICY_EOSAGO fpe
JOIN RSA_EGARANT.DRAFT_POLICY dp ON fpe.DRAFT_POLICY_ID = dp.DRAFT_POLICY_ID
where dp.APPLICATION_ID IN (
'2407920610'
 )
AND dp.END_DATE = TO_DATE('01.01.9000 00:00:00','dd.mm.yyyy hh24:mi:ss')
;

SELECT * FROM FRAUD_POLICY_EOSAGO fpe WHERE ROWNUM = 1;

SELECT * FROM RSA_EGARANT.DRAFT_POLICY dp
  JOIN RSA_EGARANT.DRAFT_POLICY_STATE dps ON dp.DRAFT_POLICY_ID = dps.DRAFT_POLICY_ID
  JOIN RSA_EGARANT.DRAFT_POLICY_STATUS dps1 ON dps.DRAFT_POLICY_STATUS_ID = dps1.DRAFT_POLICY_STATUS_ID
  WHERE dp.APPLICATION_ID = '2188200023' AND dp.END_DATE = TO_DATE('01.01.9000');

SELECT * FROM RSA_EGARANT.EVENT_LOG el WHERE el.EVENT_DATE >= TRUNC(sysdate);

SELECT * FROM RSA_EGARANT.EVENT_TYPE et ORDER by et.EVENT_TYPE_ID;

SELECT * FROM RSA_EGARANT.INS_COMPANY ic WHERE ic.INS_COMPANY_ID = '206';

SELECT * FROM RSA_EGARANT.INS_COMPANY ic WHERE ic.INSURER_ID = '13900000';

SELECT * FROM RSA_EGARANT.VALIDATION_SETTINGS vs;

SELECT * FROM RSA_EGARANT.NSI_KT;

WITH new_draft AS (SELECT COUNT(*) c
      FROM (SELECT dp.DRAFT_POLICY_ID,
                   MIN(dp.BEG_DATE)
          FROM RSA_EGARANT.DRAFT_POLICY dp
          GROUP BY dp.DRAFT_POLICY_ID
          HAVING MIN(dp.BEG_DATE) >= SYSDATE - :N / 24 / 60)), --первое число: количество минут назад от текущих дата/время
  new_epg AS (SELECT COUNT(*) c
      FROM (SELECT dp.DRAFT_POLICY_ID,
                   MIN(dp.BEG_DATE)
          FROM RSA_EGARANT.DRAFT_POLICY dp
            JOIN RSA_EOSAGO.EPOLICY e
              ON dp.INS_COMPANY_ID = e.INS_COMPANY_ID
              AND dp.INS_COMP_DRAFT_POLICY_ID = e.INS_COMP_DRAFT_POLICY_ID
              AND e.POLICY_STATE_ID = 1
          GROUP BY dp.DRAFT_POLICY_ID
          HAVING MIN(dp.BEG_DATE) >= SYSDATE - :N / 24 / 60)), --первое число: количество минут назад от текущих дата/время
  new_eosago AS
  (SELECT COUNT(e.POLICY_REC_ID) c
      FROM RSA_EOSAGO.EPOLICY e
        JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj
          ON e.POLICY_PROC_ID = ppj.POLICY_PROC_ID
      WHERE e.POLICY_STATE_ID = 1
        AND e.IS_EGARANT = 0
        AND ppj.PROC_BEG_DATE >= SYSDATE - :N / 24 / 60) --первое число: количество минут назад от текущих дата/время
SELECT nd.C "Новых заявлений за 20 минут",
       ne.C "Новых ЕПГ за :N минут",
       neo.C "Новых ЕОСАГО за :N минут"
  FROM new_draft nd,
       new_epg ne,
       new_eosago neo;


SELECT * FROM RSA_EGARANT.INS_PREM_CALC_FORMULA ipcf;

SELECT * FROM RSA_EGARANT.NSI_KOEF_KM nkk;

SELECT * FROM RSA_EGARANT.INS_COMPANY ic;

SELECT * FROM RSA_EGARANT.EVENT_LOG el 
  LEFT JOIN RSA_EGARANT.EVENT_TYPE et ON el.EVENT_TYPE_ID = et.EVENT_TYPE_ID
  WHERE el.APPLICATION_ID = '2537398910' ORDER by el.EVENT_DATE;

SELECT
  * 
  FROM RSA_EGARANT.DRAFT_POLICY dp
  JOIN RSA_EGARANT.DRAFT_POLICY_STATE dps ON dp.DRAFT_POLICY_ID = dps.DRAFT_POLICY_ID
  WHERE dp.APPLICATION_ID = '2299133350'
  AND dp.END_DATE = TO_DATE('01.01.9000 0:00:00','dd.mm.yyyy hh24:mi:ss');

SELECT * FROM RSA_EGARANT.EVENT_LOG el JOIN RSA_EGARANT.EVENT_TYPE et ON el.EVENT_TYPE_ID = et.EVENT_TYPE_ID
  WHERE el.APPLICATION_ID = '2568717496' ORDER by el.EVENT_DATE;

SELECT * FROM RSA_EGARANT.CHECK_INS_DOC_STATUS cids;