SELECT
kj.INS_REQ_ID "ID расчета КБМ",
ncb.KBM_VALUE "Значение КБМ из расчета",
kj.CREATE_DATE "Дата расчета",
po.BSO_FULL_NUM "Серия и Номер БСО",
po.INS_COMP_POLICY_ID "ID договора",
po.IS_FULL_YEAR "Признак полного года",
po.IS_RESTRICT "Признак ограничения",
po.POLICY_CREATE_DATE "Дата заключения договора",
po.POLICY_BEG_DATE "Дата начала действия",
po.POLICY_END_DATE "Дата окончания",
po.POLICY_AGGR_ID "ID Доп.соглашения",
-------------
so.SUBJ_HASH "ХЕШ",
dt.DOC_TYPE "Тип документа",
sd.DOC_FULL_NUM "Полный номер документа",
pi.LAST_NAME "Фамилия",
pi.FIRST_NAME "Имя",
pi.MIDDLE_NAMES "Отчество",
pi.BIRTH_DATE "Дата рождения",
---------------
so1.SUBJ_HASH "ХЕШ add",
dt1.DOC_TYPE "Тип документа add",
sd1.DOC_FULL_NUM "Полный номер документа add",
pi1.LAST_NAME "Фамилия add",
pi1.FIRST_NAME "Имя add",
pi1.MIDDLE_NAMES "Отчество add",
pi1.BIRTH_DATE "Дата рождения add",
--------------
kppl.LOSS_ID,
kppl.LOSS_DECISION_ID,
lpj.MPQD "Мин. дата загрузки убытка",
kes.STATUS,
kcsd.*
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_PHYSICAL_PERSON_CALC kppc ON kj.KBM_PHYSICAL_PERSON_CALC_ID = kppc.KBM_PHYSICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_PHYSICAL_PERSON kpp ON kppc.KBM_PHYSICAL_PERSON_CALC_ID = kpp.KBM_PHYSICAL_PERSON_CALC_ID
--JOIN RSA2.SUBJECT_OSAGO so ON kpp.SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
--JOIN RSA2.SUBJ_DOC sd ON so.SUBJ_OSAGO_DOC_REC_ID = sd.DOC_REC_ID
--JOIN RSA1.PERSONAL_INFO pi ON so.SUBJ_HASH = pi.SUBJ_HASH
join RSA1.NSI_CLASS_BM ncb ON kppc.KBM_ID = ncb.CLASS_BM_ID
LEFT JOIN RSA1.POLICY_OSAGO po ON kppc.POLICY_REC_ID = po.POLICY_REC_ID

left JOIN RSA2.KBM_PHYSICAL_PERSON_LOSS kppl ON kppc.KBM_PHYSICAL_PERSON_CALC_ID = kppl.KBM_PHYSICAL_PERSON_CALC_ID
  LEFT JOIN (SELECT MIN(PROC_QUEUE_DATE) MPQD,LOSS_REC_ID,LOSS_DECISION_ID FROM RSA1.LOSS_PROCESS_JUR GROUP by LOSS_REC_ID,LOSS_DECISION_ID) lpj
  
  ON kppl.LOSS_ID = lpj.LOSS_REC_ID AND kppl.LOSS_DECISION_ID = lpj.LOSS_DECISION_ID
LEFT JOIN RSA2.KBM_PLUS_PHYSICAL_PERSON_LOSS kpppl ON kppc.KBM_PHYSICAL_PERSON_CALC_ID = kpppl.KBM_PHYSICAL_PERSON_CALC_ID

join RSA1.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA1.SUBJ_DOC sd ON so.SUBJ_OSAGO_DOC_REC_ID = sd.DOC_REC_ID
JOIN RSA1.PERSONAL_INFO pi ON so.SUBJ_HASH = pi.SUBJ_HASH
JOIN RSA1.DOC_TYPE dt ON sd.DOC_TYPE_ID = dt.DOC_TYPE_ID

LEFT JOIN RSA1.SUBJECT_OSAGO so1 ON kj.ADDITIONAL_SUBJ_OSAGO_REC_ID = so1.SUBJ_OSAGO_REC_ID
LEFT JOIN RSA1.SUBJ_DOC sd1 ON so1.SUBJ_OSAGO_DOC_REC_ID = sd1.DOC_REC_ID
LEFT JOIN RSA1.PERSONAL_INFO pi1 ON so1.SUBJ_HASH = pi1.SUBJ_HASH
LEFT JOIN RSA1.DOC_TYPE dt1 ON sd1.DOC_TYPE_ID = dt1.DOC_TYPE_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kppc.KBM_PHYSICAL_PERSON_CALC_ID = kes.KBM_PHYSICAL_PERSON_CALC_ID
LEFT JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
/*
WHERE LOWER(pi.LAST_NAME) = LOWER('Шамина')
AND LOWER(pi.FIRST_NAME) = LOWER('Анастасия')
AND LOWER(pi.MIDDLE_NAMES) = LOWER('Александровна')
AND pi.BIRTH_DATE = TO_DATE('25.06.1990','dd.mm.yyyy')
ORDER BY "Дата расчета"
;*/
where kj.INS_REQ_ID = '7609272273';
