WITH PTS AS (
 SELECT  ic.INS_COMPANY_ID,
         ic.INS_COMPANY,
         pd1.CALCULATION_DATE,
         pd.PTS_NUMBER/*,
         pd1.STATUS*/
    FROM PTS_DISTRIBUTION pd 
    JOIN PRINCIPAL_DETERMINE pd1 ON pd.PRINCIPAL_DETERMINE_ID = pd1.PRINCIPAL_DETERMINE_ID
    JOIN INS_COMPANY ic ON pd1.INS_COMPANY_ID = ic.INS_COMPANY_ID
    WHERE pd1.CALCULATION_DATE >= TO_DATE('28.06.17')
    ---AND ic.INS_COMPANY_ID = '10'
    order BY ic.INS_COMPANY_ID
)
--SELECT INS_COMPANY_ID,COUNT(*) FROM (
SELECT * FROM PTS WHERE INS_COMPANY_ID = '10' and rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '12' AND rownum <= 10
UNION 
SELECT * FROM PTS WHERE INS_COMPANY_ID = '14' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '18' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '19' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '20' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '24' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '26' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '200' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '201' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '202' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '203' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '206' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '208' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '209' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '211' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '212' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '213' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '214' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '216' AND rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '217' AND  rownum <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '219' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '222' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '223' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '224' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '225' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '230' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '231' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '232' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '234' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '237' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '241' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '242' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '244' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '245' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '247' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '248' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '251' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '252' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '254' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '257' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '258' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '262' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '263' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '267' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '269' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '271' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '272' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '273' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '274' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '278'  AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '280'  AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '281'  AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '283'  AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '285'   AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '287' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '352' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '355' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '358' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '359' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '226' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '228' AND ROWNUM <= 10
UNION
SELECT * FROM PTS WHERE INS_COMPANY_ID = '227' AND ROWNUM <= 10
--)GROUP BY INS_COMPANY_ID
;

SELECT
irj.INS_REQ_JOUR_ID "ID запроса от СК",
ic.INS_COMPANY "Наименование СК",
irj.INS_COMPANY_ID "ID СК",
rt.REQ_TYPE "Тип запроса",
rs.REQ_STATUS "Статус обработки запроса",
irj.BEG_DATE "Дата получения запроса",
irj.END_DATE "Дата ответа на запрос",
irj.REQ_STATUS_MESSAGE "Описание ошибки",
ht.HANDLE_NAME "Подтип запроса"
FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON ppj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID
JOIN RSA_EOSAGO.REQUEST_TYPE rt ON irj.REQ_TYPE_ID = rt.REQ_TYPE_ID
JOIN REQUEST_STATUS rs ON irj.REQ_STATUS_ID = rs.REQ_STATUS_ID
JOIN RSA_EOSAGO.HANDLE_TYPE ht ON ppj.HANDLE_TYPE_ID = ht.HANDLE_TYPE_ID
WHERE ROWNUM <= 3 AND ppj.HANDLE_TYPE_ID = '11' AND irj.REQ_TYPE_ID = '36'
order by ppj.PROC_QUEUE_DATE;



SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
WHERE ppj.INS_COMP_DRAFT_POLICY_ID IN (SELECT e.INS_COMP_DRAFT_POLICY_ID FROM RSA_EOSAGO.EPOLICY e WHERE e.POLICY_NUMBER = '0000816082')
--AND ppj.INS_COMPANY_ID = '251'
order by ppj.PROC_QUEUE_DATE;

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj LEFT JOIN RSA_EOSAGO.POLICY_PROCESS_ERR ppe ON ppj.POLICY_PROC_ID = ppe.POLICY_PROC_ID
WHERE ppj.POLICY_NUMBER = '0000811727'
--AND ppj.INS_COMPANY_ID = '267'
--WHERE ppj.TRIP_NUM = 'e3dfc409-3c8d-11e7-80dd-000c29551b87'
--where ppj.INS_COMP_DRAFT_POLICY_ID = 'PE_1720prm00000006820'
order by proc_end_date;