SELECT * FROM RSA1.BSO_REQUEST_JOURNAL brj 
JOIN RSA1.BSO_PACKAGE_JOURNAL bpj ON brj.BSO_PACKAGE_JOURNAL_ID = bpj.BSO_PACKAGE_JOURNAL_ID
JOIN RSA1.INS_REQUEST_JUR irj ON bpj.INS_REQ_ID = irj.INS_REQ_ID
JOIN RSA1.BSO_STATE bs ON brj.BSO_STATE_ID = bs.BSO_STATE_ID
JOIN RSA1.BSO b ON bs.BSO_ID = b.BSO_ID
WHERE ROWNUM < 2 AND brj.REVOKE_MID IS NOT NULL
--AND b.BSO_SERIES = 'еее'
--AND  b.BSO_NUMBER = '1007586948'
;


SELECT * FROM RSA1.BSO_REQUEST_JOURNAL brj 
JOIN RSA1.BSO_PACKAGE_JOURNAL bpj ON brj.BSO_PACKAGE_JOURNAL_ID = bpj.BSO_PACKAGE_JOURNAL_ID
JOIN RSA1.INS_REQUEST_JUR irj ON bpj.INS_REQ_ID = irj.INS_REQ_ID
JOIN RSA1.BSO_STATE bs ON brj.BSO_STATE_ID = bs.BSO_STATE_ID
JOIN RSA1.BSO b ON bs.BSO_ID = b.BSO_ID
WHERE /*ROWNUM < 2 --AND brj.REVOKE_MID IS NOT NULL
AND*/ b.BSO_SERIES = 'еее'
AND  b.BSO_NUMBER = '1002871226';


SELECT * FROM RSA1.BSO_REQUEST_JOURNAL brj
LEFT JOIN RSA1.BSO_REQUEST_ERROR bre ON brj.BSO_REQUEST_JOURNAL_ID = bre.BSO_REQUEST_JOURNAL_ID
JOIN RSA1.BSO_PACKAGE_JOURNAL bpj ON brj.BSO_PACKAGE_JOURNAL_ID = bpj.BSO_PACKAGE_JOURNAL_ID
LEFT JOIN RSA1.BSO_PACKAGE_ERROR bpe ON bpj.BSO_PACKAGE_JOURNAL_ID = bpe.BSO_PACKAGE_JOURNAL_ID
JOIN RSA1.INS_REQUEST_JUR irj ON bpj.INS_REQ_ID = irj.INS_REQ_ID
WHERE brj.BSO_NUMBER = '1002871226';
