SELECT * FROM RSA_EOSAGO.REQUEST_TYPE rt ORDER BY rt.REQ_TYPE_ID;

--30	Запрос на проверку субъекта – страхователя/собственника ТС
--31	Запрос статуса обр. запр. на пров. суб.–стр-ля/собств. ТС
--32	Запрос на проверку субъекта – ЛДУ
--33	Запрос статуса обработки запроса на проверку субъекта – ЛДУ
--34	Запрос на проверку ТС
--35	Запрос статуса обработки запроса на проверку ТС

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = 10 AND irj.REQ_TYPE_ID IN (30,32,34) AND irj.BEG_DATE >= TRUNC(sysdate) /*AND irj.REQ_STATUS_ID =3*/;
SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = 10 AND irj.REQ_TYPE_ID IN (31) AND irj.BEG_DATE >= TRUNC(sysdate);
SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE 1=1 irj.INS_COMPANY_ID = 19 AND irj.REQ_TYPE_ID IN (30,31,32,33,34,35) AND irj.BEG_DATE >= TRUNC(SYSDATE,'hh') AND irj.REQ_STATUS_ID = 3 ORDER BY irj.BEG_DATE DESC;
SELECT
  * 
  FROM RSA_EOSAGO.CHECK_OWNER_REQUEST_JOUR corj
  JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON corj.CHECK_REQ_ID = crj.CHECK_REQ_ID
  JOIN RSA_EOSAGO.INS_REQUEST_JOUR irj ON crj.INS_REQ_JOUR_ID = irj.INS_REQ_JOUR_ID
  WHERE corj.SUBJ_HASH = 'E3BAD68F65B7D8A48D5BC160A040047F2000F9210C1B989F48053BD95F6A5851' ORDER by crj.PROC_END_DATE;

SELECT
  * 
  FROM RSA_EOSAGO.CHECK_OWNER_REQUEST_JOUR corj
  JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON corj.CHECK_REQ_ID = crj.CHECK_REQ_ID
  WHERE crj.PROC_BEG_DATE >= TRUNC(SYSDATE,'hh')
  ORDER by crj.PROC_END_DATE DESC;

SELECT * FROM RSA_EOSAGO.CHECK_REQUEST_JOUR crj WHERE crj.CHECK_REQ_ID IN (
SELECT MAX(check_req_id) FROM RSA_EOSAGO.CHECK_REQUEST_JOUR crj WHERE crj.PROC_QUEUE_DATE >= TRUNC(SYSDATE,'hh') AND crj.PROC_BEG_DATE IS NOT NULL
);

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '1468280134';

SELECT
  * 
  FROM RSA_EOSAGO.DKBM_SENT_CHECK_JOUR dscj
  WHERE dscj.PROC_BEG_DATE >= TRUNC(SYSDATE, 'hh')
  ORDER BY dscj.PROC_BEG_DATE DESC; --WHERE dscj.PROC_BEG_DATE >= TRUNC(sysdate);

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
WHERE crj.INS_REQ_JOUR_ID = '2011369458';

SELECT * FROM RSA_EOSAGO.QUEUE_2 q;



SELECT 
COUNT (*),qcm.REGION
FROM RSA_EOSAGO.QUEUE_CHANNEL_MESSAGE qcm GROUP BY qcm.REGION;

SELECT min(qcm.CREATED_DATE) FROM RSA_EOSAGO.QUEUE_CHANNEL_MESSAGE qcm WHERE ROWNUM < 2;

SELECT COUNT(*), pcm.REGION,  SYSDATE FROM RSA_EOSAGO.POLICY_CHANNEL_MESSAGE pcm GROUP BY pcm.REGION;

WITH IRJI AS (
SELECT
  irj.INS_REQ_JOUR_ID,
  irj.REQ_TYPE_ID,
  ic.INS_COMPANY,
  trunc(irj.BEG_DATE, 'mi') - mod(EXTRACT(minute FROM irj.BEG_DATE), 10) / (24 * 60) DB
  FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
  JOIN RSA_EOSAGO.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE irj.REQ_TYPE_ID IN (30,31,32,33,34,35)
  AND beg_date >= TO_DATE('21.02.2019 08:00', 'dd.mm.yyyy hh24:mi')
  AND beg_date < TO_DATE('21.02.2019 10:00', 'dd.mm.yyyy hh24:mi')
)
SELECT * FROM IRJI PIVOT (COUNT(INS_REQ_JOUR_ID) FOR (REQ_TYPE_ID) in (30,31,32,33,34,35)) order by db;

WITH IRJI AS (
SELECT
  irj.INS_REQ_JOUR_ID,
  irj.REQ_TYPE_ID,
  ic.INS_COMPANY,
  trunc(irj.BEG_DATE, 'mi') - mod(EXTRACT(minute FROM irj.BEG_DATE), 10) / (24 * 60) DB
  FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
  JOIN RSA_EOSAGO.INS_COMPANY ic ON irj.INS_COMPANY_ID = ic.INS_COMPANY_ID
  WHERE irj.REQ_TYPE_ID IN (30,31,32,33,34,35)
  AND ic.INS_COMPANY_ID = 19
  AND beg_date >= TO_DATE('21.02.2019 10:00', 'dd.mm.yyyy hh24:mi')
  AND beg_date < TO_DATE('21.02.2019 18:00', 'dd.mm.yyyy hh24:mi')
)
SELECT * FROM IRJI PIVOT (COUNT(INS_REQ_JOUR_ID) FOR (REQ_TYPE_ID) in (30,31,32,33,34,35)) order by db;

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE irj.INS_REQ_JOUR_ID = '2011369458';

SELECT * FROM RSA_EOSAGO.CHECK_VEHICLE_REQUEST_JOUR cvrj JOIN RSA_EOSAGO.CHECK_REQUEST_JOUR crj ON cvrj.CHECK_REQ_ID = crj.CHECK_REQ_ID
  WHERE crj.INS_REQ_JOUR_ID = '1468565727';

SELECT * FROM RSA_EOSAGO.INS_COMPANY ic;