SELECT
*
  FROM BSI1.LOSS_KASKO lk;

SELECT
  * 
  FROM BSI1.POLICY_KASKO pk
  JOIN BSI1.POLICY_OWNER_INFO poi ON pk.POLICY_REC_ID = poi.POLICY_REC_ID
  --JOIN BSI1.
  where pk.INS_COMP_POLICY_ID = '9182779895019';

SELECT
  * 
  FROM BSI1.LOSS_PROCESS_JOUR lpj
  JOIN BSI1.TRIP_IMP_JOUR tij ON lpj.TRIP_ID = tij.TRIP_ID
  WHERE lpj.PROC_QUEUE_DATE>= TRUNC(sysdate);


SELECT
  * 
  FROM BSI1.LOSS_KASKO lk
  JOIN BSI1.POLICY_KASKO pk ON lk.POLICY_REC_ID = pk.POLICY_REC_ID
  JOIN BSI1.POLICY_OWNER_INFO poi ON pk.POLICY_REC_ID = poi.POLICY_REC_ID
  --JOIN BSI1.CAR_OWNER_INFO coi ON poi.SUBJ_OSAGO_REC_ID = coi.SUBJ_OSAGO_REC_ID
  WHERE lk.INS_COMP_LOSS_ID = '0012875745';

SELECT
  * 
  FROM BSI1.POLICY_PROCESS_JOUR ppj 
  JOIN BSI1.TRIP_IMP_JOUR tij ON ppj.TRIP_ID = tij.TRIP_ID
  WHERE ppj.INS_COMP_POLICY_ID = '9182779895019' ORDER BY ppj.PROC_QUEUE_DATE;

SELECT
  COUNT(lk.LOSS_REC_ID) 
  FROM BSI1.LOSS_KASKO lk
  JOIN BSI1.POLICY_KASKO pk ON lk.POLICY_REC_ID = pk.POLICY_REC_ID
  WHERE lk.IS_TECH_COR = 0
  AND lk.RECALL_LOSS_REC_ID = 0
  AND pk.IS_TECH_COR = 0
  AND pk.RECALL_POLICY_UNQ_ID = 0;

--1 865 338

SELECT
  COUNT(DISTINCT lk.LOSS_REC_ID) 
  FROM BSI1.LOSS_KASKO lk
  JOIN BSI1.LOSS_PROCESS_JOUR lpj ON lk.LOSS_REC_ID = lpj.LOSS_REC_ID
  JOIN BSI1.POLICY_KASKO pk ON lk.POLICY_REC_ID = pk.POLICY_REC_ID
  WHERE lk.IS_TECH_COR = 0
  AND lk.RECALL_LOSS_REC_ID = 0
  AND pk.IS_TECH_COR = 0
  AND pk.RECALL_POLICY_UNQ_ID = 0;


WITH COMPANY AS (
SELECT 
ic.INS_COMPANY,
ic.INS_COMPANY_ID  
FROM BSI1.INS_COMPANY ic  
),

INN_LOSS AS (
SELECT
  COUNT(DISTINCT lk.LOSS_REC_ID) lri,
  lk.INS_COMPANY_ID
  FROM BSI1.LOSS_KASKO lk
  JOIN BSI1.LOSS_PROCESS_JOUR lpj ON lk.LOSS_REC_ID = lpj.LOSS_REC_ID
  JOIN BSI1.POLICY_KASKO pk ON lk.POLICY_REC_ID = pk.POLICY_REC_ID
  JOIN BSI1.POLICY_OWNER_INFO poi ON pk.POLICY_REC_ID = poi.POLICY_REC_ID
  WHERE lk.IS_TECH_COR = 0
  AND lk.RECALL_LOSS_REC_ID = 0
  AND pk.IS_TECH_COR = 0
  AND pk.RECALL_POLICY_UNQ_ID = 0
  AND poi.ORG_ID IS NOT NULL
  --AND poi.INN_INDIVID IS not null
  AND lpj.PROC_QUEUE_DATE >= TO_DATE('01.01.2018')
  GROUP BY lk.INS_COMPANY_ID
),
FIZ_LOSS AS (
SELECT
  COUNT(DISTINCT lk.LOSS_REC_ID) lri,
  lk.INS_COMPANY_ID
  FROM BSI1.LOSS_KASKO lk
  JOIN BSI1.LOSS_PROCESS_JOUR lpj ON lk.LOSS_REC_ID = lpj.LOSS_REC_ID
  JOIN BSI1.POLICY_KASKO pk ON lk.POLICY_REC_ID = pk.POLICY_REC_ID
  JOIN BSI1.POLICY_OWNER_INFO poi ON pk.POLICY_REC_ID = poi.POLICY_REC_ID
  WHERE lk.IS_TECH_COR = 0
  AND lk.RECALL_LOSS_REC_ID = 0
  AND pk.IS_TECH_COR = 0
  AND pk.RECALL_POLICY_UNQ_ID = 0
  AND poi.ORG_ID IS NULL
  --AND poi.INN_INDIVID IS not null
  AND lpj.PROC_QUEUE_DATE >= TO_DATE('01.01.2018')
  GROUP BY lk.INS_COMPANY_ID
)
SELECT
c.INS_COMPANY,
NVL(il.lri,'0') "Кол-во убытков ЮЛ",
NVL(fl.lri,'0') "Кол-во убытков ФЛ"
FROM COMPANY c
LEFT JOIN INN_LOSS il ON c.INS_COMPANY_ID = il.INS_COMPANY_ID
LEFT JOIN FIZ_LOSS fl ON c.INS_COMPANY_ID = fl.INS_COMPANY_ID
WHERE c.INS_COMPANY != ':F'
;
--711643