UPDATE rsa_epg_web.ins_company  SET INS_COMPANY = '"АльфаСтрахование" АО' WHERE INS_COMPANY_ID = '262';
UPDATE rsa_epg_web.ins_company  SET INS_COMPANY = '"Ангара" ООО Страховая компания' WHERE INS_COMPANY_ID = '241';
UPDATE rsa_epg_web.ins_company  SET INS_COMPANY = '"БАСК" АО СК' WHERE INS_COMPANY_ID = '251';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ВСК" САО' WHERE INS_COMPANY_ID = '206';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Ингосстрах" СПАО' WHERE INS_COMPANY_ID = '20';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Капитал Страхование" ОАО' WHERE INS_COMPANY_ID = '216';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"МАКС" АО' WHERE INS_COMPANY_ID = '19';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Медэкспресс" САО' WHERE INS_COMPANY_ID = '223';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Московия" ООО СК' WHERE INS_COMPANY_ID = '248';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"УралСиб" АО Страховая группа' WHERE INS_COMPANY_ID = '243';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ПАРИ" АО СК' WHERE INS_COMPANY_ID = '214';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РЕСО-Гарантия" СПАО' WHERE INS_COMPANY_ID = '269';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Росгосстрах" ПАО СК' WHERE INS_COMPANY_ID = '10';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Согласие" ООО СК' WHERE INS_COMPANY_ID = '201';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Сургутнефтегаз" ООО Страховое общество' WHERE INS_COMPANY_ID = '267';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЭНЕРГОГАРАНТ" ПАО САК' WHERE INS_COMPANY_ID = '219';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ИНТАЧ СТРАХОВАНИЕ" АО' WHERE INS_COMPANY_ID = '231';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЭНИ" ОАО СК' WHERE INS_COMPANY_ID = '261';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Югория" АО ГСК' WHERE INS_COMPANY_ID = '26';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"АСКО-СТРАХОВАНИЕ" ПАО' WHERE INS_COMPANY_ID = '252';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"АСКО" ООО СГ' WHERE INS_COMPANY_ID = '225';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Боровицкое страховое общество" АО' WHERE INS_COMPANY_ID = '265';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СК Гайде" ОАО' WHERE INS_COMPANY_ID = '18';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СДС" ООО Страховая компания' WHERE INS_COMPANY_ID = '237';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ГУТА-Страхование" АО' WHERE INS_COMPANY_ID = '266';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ДАЛЬАКФЕС" ООО СК' WHERE INS_COMPANY_ID = '278';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Армеец" АО СК' WHERE INS_COMPANY_ID = '232';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Либерти Страхование" АО' WHERE INS_COMPANY_ID = '228';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Мегарусс-Д" ООО СК' WHERE INS_COMPANY_ID = '247';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Мед-Гарант" АО СК' WHERE INS_COMPANY_ID = '234';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Спасские ворота" АО СГ' WHERE INS_COMPANY_ID = '230';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Надежда" САО' WHERE INS_COMPANY_ID = '244';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Зетта Страхование" ООО' WHERE INS_COMPANY_ID = '254';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"НАСКО" АО' WHERE INS_COMPANY_ID = '24';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Подмосковье" АО СК' WHERE INS_COMPANY_ID = '208';  
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ПОЛИС-ГАРАНТ" АО Страховая Компания' WHERE INS_COMPANY_ID = '257';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СГ МСК" АО' WHERE INS_COMPANY_ID = '21';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РЕГИОНГАРАНТ" АО СК' WHERE INS_COMPANY_ID = '224';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Группа Ренессанс Страхование" АО' WHERE INS_COMPANY_ID = '12';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РОСЭНЕРГО" ООО НСГ' WHERE INS_COMPANY_ID = '222';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЭРГО" САО' WHERE INS_COMPANY_ID = '242';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ОСК" АО' WHERE INS_COMPANY_ID = '263';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Астро-Волга" АО СК' WHERE INS_COMPANY_ID = '226';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СЕРВИСРЕЗЕРВ" ООО СК' WHERE INS_COMPANY_ID = '274';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СТРАЖ" ООО МСК' WHERE INS_COMPANY_ID = '273';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СОГАЗ" АО' WHERE INS_COMPANY_ID = '217';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РИКС" ООО' WHERE INS_COMPANY_ID = '236';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Чулпан" АО СК' WHERE INS_COMPANY_ID = '227';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РЕСО-Шанс" ООО СК' WHERE INS_COMPANY_ID = '238';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЯКОРЬ" АО Страховое Общество' WHERE INS_COMPANY_ID = '258';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Талисман" АО СО' WHERE INS_COMPANY_ID = '209';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЦСО" ООО' WHERE INS_COMPANY_ID = '211';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Страховая бизнес группа" АО' WHERE INS_COMPANY_ID = '213';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ПСА" ООО' WHERE INS_COMPANY_ID = '245';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Двадцать первый век" ЗАО СК' WHERE INS_COMPANY_ID = '203';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"БИН Страхование" ООО' WHERE INS_COMPANY_ID = '272';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Геополис" ООО СО' WHERE INS_COMPANY_ID = '200';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ХОСКА" ПАО СГ' WHERE INS_COMPANY_ID = '283';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ВТБ Страхование" ООО СК' WHERE INS_COMPANY_ID = '14';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Паритет-СК" ООО СК' WHERE INS_COMPANY_ID = '202';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Сибирский Спас" АО СК' WHERE INS_COMPANY_ID = '202';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РЕЗОНАНС" ООО БСК' WHERE INS_COMPANY_ID = '264';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ПРОМИНСТРАХ" ООО' WHERE INS_COMPANY_ID = '229';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Тинькофф Страхование" АО' WHERE INS_COMPANY_ID = '281';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЕВРОИНС" ООО РСО' WHERE INS_COMPANY_ID = '212';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Стерх" АО СК' WHERE INS_COMPANY_ID = '271';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Гелиос" ООО Страховая Компания' WHERE INS_COMPANY_ID = '285';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Абсолют Страхование" ООО' WHERE INS_COMPANY_ID = '287';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Адонис" ООО СФ' WHERE INS_COMPANY_ID = '352';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ЮЖУРАЛЖАСО" АО' WHERE INS_COMPANY_ID = '355';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"РГС" ОАО' WHERE INS_COMPANY_ID = '357';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"СК Опора" АО' WHERE INS_COMPANY_ID = '358';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"ВЕРНА" ООО СО' WHERE INS_COMPANY_ID = '359';
update rsa_epg_web.ins_company  SET INS_COMPANY = '"Диамант" ООО СК' WHERE INS_COMPANY_ID = '1065';


commit;