SELECT *
/*
DISTINCT
so.INN,
so.ORG_NAME,
kjpc.*
*/
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' /*AND kj.INS_REQ_ID = '7941691398'*/
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy') 
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy')
AND KJ.KBM_JURIDICAL_PERSON_CALC_ID = 2505502
;

SELECT *
/*
DISTINCT
so.INN,
so.ORG_NAME,
kjpc.*
*/
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
--JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' /*AND kj.INS_REQ_ID = '7941691398'*/
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy') 
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy')
AND KJ.KBM_JURIDICAL_PERSON_CALC_ID = 2502774
;


--SELECT * FROM rsa2.KBM_LOG;

--KBM_JURIDICAL_PERSONAL_CALC_ID
--2505502
--2497800
--2502774

SELECT 
DISTINCT
so.SUBJ_OSAGO_REC_ID,
so.SUBJ_OSAGO_UNQ_ID,
so.INN,
so.ORG_NAME,
kjpc.*
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
--JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' /*AND kj.INS_REQ_ID = '7941691398'*/
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy') 
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy') ORDER BY kjpc.CREATE_DATE;

SELECT *
FROM RSA2.TEMP_AUTO_CALC_KBM_2019 tack WHERE TACK.INN = 7709378229;

SELECT * FROM rsa2.TEMP_JUR_WITH_HUGE_AUTOPARK "tjwha" WHERE "tjwha".INN = '7709378229';

select t.*, t.rowid from RSA1.LOG_TABLE_UTIL t
where t.created between TO_DATE('09.09.2019','dd.mm.yyyy') and TO_DATE('10.09.2019','dd.mm.yyyy')
and t.text like '%292352135%'  --subj_osago_unq_id = '183708245'
order by t.created;

select t.*, t.rowid from RSA1.LOG_TABLE_UTIL t
where t.created between TO_DATE('18.09.2019','dd.mm.yyyy') and TO_DATE('19.09.2019','dd.mm.yyyy')
and t.text like '%183708245%'  --subj_osago_unq_id = '183708245'
order by t.created;

SELECT * FROM rsa1.subject_osago so WHERE so.SUBJ_OSAGO_UNQ_ID  = '183708245';


WITH TT1 AS (
SELECT
TRIM(REPLACE(SUBSTR(ltu.text,60,9),',')) AS UNQ
FROM RSA1.LOG_TABLE_UTIL ltu
WHERE  ltu.created between TO_DATE('09.09.2019','dd.mm.yyyy') and TO_DATE('10.09.2019','dd.mm.yyyy') --AND LTU.LOG_TYPE LIKE '%_SpW%'
)
SELECT * FROM TT1
WHERE UNQ IN (
SELECT SO.SUBJ_OSAGO_UNQ_ID FROM rsa1.SUBJECT_OSAGO so WHERE SO.INN = '7709378229'
)
;
WITH TT1 AS (
SELECT
TRIM(REPLACE(SUBSTR(ltu.text,27,9),',')) AS SORI
FROM RSA1.LOG_TABLE_UTIL ltu
WHERE  ltu.created between TO_DATE('18.09.2019','dd.mm.yyyy') and TO_DATE('19.09.2019','dd.mm.yyyy')
)
SELECT * FROM TT1
WHERE SORI IN (
SELECT SO.SUBJ_OSAGO_REC_ID FROM rsa1.SUBJECT_OSAGO so WHERE SO.INN = '7709378229'
);


SELECT * FROM rsa1.SUBJECT_OSAGO so WHERE SO.INN = '7709378229';

SELECT * FROM rsa1.SUBJECT_OSAGO so WHERE SO.SUBJ_OSAGO_REC_ID = '292352135';

SELECT * FROM rsa1.LOG_TABLE_UTIL ltu WHERE  ltu.created between TO_DATE('09.09.2019','dd.mm.yyyy') and TO_DATE('10.09.2019','dd.mm.yyyy');

WITH TT1 AS (
SELECT
created,
text,
log_type,
TRIM(REPLACE(SUBSTR(ltu.text,27,9),',')) AS SORI
FROM RSA1.LOG_TABLE_UTIL ltu
WHERE  ltu.created between TO_DATE('01.09.2019','dd.mm.yyyy') and TO_DATE('18.10.2019','dd.mm.yyyy')
),
TT2 AS (
SELECT
*
FROM TT1
WHERE SORI IN (
SELECT SO.SUBJ_OSAGO_REC_ID FROM rsa1.SUBJECT_OSAGO so 
WHERE so.INN IS NOT NULL
AND SO.IS_JURIDICAL = 1
--SO.INN = '7709378229'
)
)
SELECT
tt2.*,
so.SUBJ_OSAGO_REC_ID,
so.SUBJ_OSAGO_UNQ_ID,
SO.SUBJ_HASH,
so.IS_JURIDICAL,
so.INN,
so.ORG_NAME,
so.IS_RESIDENT,
so.IS_FROM_BSI,
so.SYS_CORR_DATE
FROM tt2
JOIN rsa1.SUBJECT_OSAGO so ON tt2.SORI = so.SUBJ_OSAGO_REC_ID;

SELECT * FROM rsa2.KBM_JURIDICAL_PERSON_CALC kjpc
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy')  AND kjpc.KBM_JURIDICAL_PERSON_CALC_ID = '2502774'
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy') ORDER BY kjpc.CREATE_DATE;

SELECT
*
from rsa2.kbm_juridical_person kjp
WHERE KJP.SUBJ_OSAGO_REC_ID IN (
'577934498',
'292388916',
'577934498',
'292388916',
'292352135',
'292352135'
) ORDER BY KJP.CREATE_DATE;



SELECT *
/*
DISTINCT
so.INN,
so.ORG_NAME,
kjpc.*
*/
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
--JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
--JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  1=1 AND kj.INS_REQ_ID = '7924118176'
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy') 
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy')
;