WITH TT1 AS (
SELECT
"tack".INN
FROM rsa2.TEMP_AUTO_CALC_KBM_2019 "tack"
WHERE "tack".KBM_JURIDICAL_PERSON_CALC_ID IS NULL
),
tt2 AS (
SELECT
INN,MAX("kjp".KBM_JURIDICAL_PERSON_CALC_ID) kjpc,"kes".STATUS
FROM rsa2.KBM_ENTITY_STATUS "kes"
JOIN rsa2.KBM_JURIDICAL_PERSON_CALC "kjpc" ON "kes".KBM_JURIDICAL_PERSON_CALC_ID = "kjpc".KBM_JURIDICAL_PERSON_CALC_ID
JOIN rsa2.KBM_JURIDICAL_PERSON "kjp" ON "kjpc".KBM_JURIDICAL_PERSON_CALC_ID = "kjp".KBM_JURIDICAL_PERSON_CALC_ID
JOIN rsa2.SUBJECT_OSAGO "so" ON "kjp".SUBJ_OSAGO_REC_ID = "so".SUBJ_OSAGO_REC_ID
WHERE "kes".STATUS = 1 AND INN IN (SELECT * FROM tt1)
GROUP BY INN,"kes".STATUS
),
tt3 AS (
SELECT
INN,MAX("kjp".KBM_JURIDICAL_PERSON_CALC_ID) kjpc,"kes".STATUS
FROM rsa2.KBM_ENTITY_STATUS "kes"
JOIN rsa2.KBM_JURIDICAL_PERSON_CALC "kjpc" ON "kes".KBM_JURIDICAL_PERSON_CALC_ID = "kjpc".KBM_JURIDICAL_PERSON_CALC_ID
JOIN rsa2.KBM_JURIDICAL_PERSON "kjp" ON "kjpc".KBM_JURIDICAL_PERSON_CALC_ID = "kjp".KBM_JURIDICAL_PERSON_CALC_ID
JOIN rsa2.SUBJECT_OSAGO "so" ON "kjp".SUBJ_OSAGO_REC_ID = "so".SUBJ_OSAGO_REC_ID
WHERE "kes".STATUS = 3 AND INN IN (SELECT * FROM tt1)
GROUP BY INN,"kes".STATUS
)

SELECT
*
FROM tt2
WHERE (inn,kjpc) NOT IN (
SELECT inn,kjpc FROM tt3
) ORDER BY INN;
