SELECT
*
FROM rsa_eosago.policy_process_jour ppj WHERE ins_req_jour_id = '1513780708';

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR irj WHERE IRJ.INS_COMPANY_ID = 19 AND IRJ.BEG_DATE >= TRUNC(SYSDATE,'mm') AND IRJ.REQ_TYPE_ID = 36 ORDER BY IRJ.BEG_DATE DESC;

SELECT * FROM RSA_EOSAGO.REQUEST_TYPE "rt" ORDER BY "rt".REQ_TYPE_ID;

SELECT LENGTH(7700000043600) FROM DUAL "d";

SELECT * FROM RSA_EOSAGO.KLADR k WHERE k.SOCR = 'г' AND K.NAME = 'Куйбышев' AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT * FROM RSA_EOSAGO.KLADR k WHERE code = '7700000043600' AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT LENGTH(770000004360000) FROM DUAL "d";

SELECT LENGTH(7700000200000000005) FROM DUAL "d";

SELECT * FROM RSA_EOSAGO.STREET s WHERE s.CODE = '78000000000087400' AND s.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT * FROM RSA_EOSAGO.DOMA d WHERE d.CODE like '%780000000000874%' AND d.NAME LIKE '%55%' AND d.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT * FROM RSA_EGARANT.nsi_kt nk
JOIN RSA_EGARANT.KLADR k ON NK.KT_ID = K.KT_ID;

SELECT MAX(K.BEG_DATE) FROM RSA_EGARANT.KLADR k WHERE k.KT_ID IS NOT NULL /*AND k.SOCR = 'г'*/ AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR "irj" WHERE "irj".REQ_TYPE_ID = '36' AND "irj".BEG_DATE >= TRUNC(SYSDATE - 1) AND "irj".BEG_DATE < TRUNC(sysdate);
SELECT * FROM RSA_EOSAGO.REQUEST_TYPE "rt" ORDER BY "rt".REQ_TYPE_ID;

SELECT * FROM RSA_EOSAGO.PERSONAL_INFO "pi" WHERE last_name = 'ДЖАНГУРАЗОВА' ;
SELECT
ppj.INS_REQ_JOUR_ID
FROM RSA_EOSAGO.SUBJECT_OSAGO so
JOIN RSA_EOSAGO.POLICY_SUBJ_INFO psi ON so.SUBJ_OSAGO_REC_ID = psi.SUBJ_OSAGO_REC_ID
JOIN RSA_EOSAGO.EPOLICY e ON psi.POLICY_REC_ID = e.POLICY_REC_ID
JOIN RSA_EOSAGO.POLICY_PROCESS_JOUR ppj ON e.POLICY_PROC_ID = ppj.POLICY_PROC_ID
WHERE so.SUBJ_HASH = '1379059A52DFC570F2585115B481220E33321F608B930EF3F95AAC7E6F4D2E09'
AND e.POLICY_CREATE_DATE >= TRUNC(SYSDATE,'mm') AND e.POLICY_STATE_ID = 3;

SELECT * FROM RSA_EOSAGO.KLADR k WHERE code = '5001400000000' AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT LENGTH(31000002000060100) FROM dual;

SELECT * FROM RSA_EOSAGO.STREET s WHERE code like '78000000000087900%' AND s.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT * FROM RSA_EOSAGO.DOMA d WHERE D.CODE LIKE '780000000000879%' AND d.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT
irj.*--,
FROM RSA_EGARANT.INS_REQUEST_JOUR irj
WHERE IRJ.INS_COMPANY_ID = 269
ORDER BY IRJ.BEG_DATE DESC;

SELECT * FROM RSA_EOSAGO.INS_COMPANY ic 
JOIN RSA_EOSAGO."USER" u ON ic.INS_COMPANY_ID = u.INS_COMPANY_ID
WHERE ic.INS_COMPANY_ID = '269';

SELECT * FROM RSA_EGARANT.NSI_VEHICLE_CATEGORY_EXTENDED "nvce";

SELECT COUNT(1) FROM RSA_EGARANT.NSI_TARIFF_BASE "ntb" WHERE "ntb".INSURER_ID = 00000007 AND "ntb".IS_ACTIVE = 1 AND "ntb".CATEGORY_TS = 'BP';

SELECT * FROM rsa_eosago.epolicy E WHERE E.POLICY_NUMBER = '0550191679';

SELECT
*
FROM RSA_EOSAGO.INS_COMPANY ic
JOIN RSA_EOSAGO."USER" "u" ON IC.INS_COMPANY_ID = "u".INS_COMPANY_ID
WHERE IC.INS_COMPANY_ID = 777;

--03000000	eQW27GEA

SELECT MAX(LENGTH(PSI.ADDRESS_APARTMENT)), PSI.POLICY_REC_ID FROM RSA_EOSAGO.POLICY_SUBJ_INFO psi GROUP BY PSI.POLICY_rec_id HAVING MAX(LENGTH(PSI.ADDRESS_APARTMENT)) > 5;

SELECT irj.*,DBMS_LOB.GETLENGTH(irj.req_body)/1024 FROM RSA_EGARANT.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = 777;

SELECT irj.*,DBMS_LOB.GETLENGTH(irj.req_body)/1024 FROM RSA_EGARANT.INS_REQUEST_JOUR irj WHERE irj.INS_COMPANY_ID = 269 ORDER BY IRJ.BEG_DATE DESC;

SELECT * FROM RSA_EOSAGO.REQUEST_TYPE "rt" ORDER BY "rt".REQ_TYPE_ID;

SELECT * FROM RSA_EOSAGO.KLADR k WHERE substr(K.CODE,3,2) != 0; 

SELECT * FROM RSA_EGARANT.event_log el
JOIN RSA_EGARANT.EVENT_TYPE et ON EL.EVENT_TYPE_ID = ET.EVENT_TYPE_ID
WHERE el.APPLICATION_ID = '1514194208';

SELECT * FROM RSA_EGARANT.PROCESS_LOADER_JOUR "plj" JOIN RSA_EGARANT.PROCESS_LOADER_TYPE "plt" ON "plj".PROCESS_LOADER_TYPE_ID = "plt".PROCESS_LOADER_TYPE_ID
WHERE "plj".APPLICATION_ID = '1514194208';

SELECT * FROM RSA_EGARANT.NSI_KT "nk";
SELECT COUNT(1) FROM RSA_EGARANT.KLADR k WHERE k.KT_ID IS NULL AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

SELECT * FROM RSA_EGARANT.KLADR k WHERE k.KT_ID IS not NULL AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

--SELECT length(4402300019300) FROM RSA_EGARANT.KLADR "k";

SELECT * FROM RSA_EGARANT.KLADR k WHERE substr(K.CODE,3,13) = 00000000000 AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');
--86 субьектов РФ

SELECT K.KT_ID FROM RSA_EGARANT.KLADR k WHERE substr(K.CODE,3,13) = 00000000000 AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy') AND K.KT_ID IS NOT NULL;
-- Из 86 субьектов РФ есть отсылка на KT - 4 штуки

SELECT
*
FROM RSA_EGARANT.NSI_KT nk 
WHERE NK.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy')
/*
AND NK.KT_ID NOT IN (
SELECT K.KT_ID FROM RSA_EGARANT.KLADR k WHERE substr(K.CODE,3,13) = 00000000000 AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy') AND K.KT_ID IS NOT NULL
)*/
 AND NK.PLACE != 'Прочие города и населенные пункты';


SELECT
*
FROM RSA_EGARANT.KLADR k
WHERE K.KT_ID IN (
SELECT
NK.KT_ID
FROM RSA_EGARANT.NSI_KT nk 
WHERE NK.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy')
/*
AND NK.KT_ID NOT IN (
SELECT K.KT_ID FROM RSA_EGARANT.KLADR k WHERE substr(K.CODE,3,13) = 00000000000 AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy') AND K.KT_ID IS NOT NULL
)*/ AND NK.PLACE != 'Прочие города и населенные пункты'
)
AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy');

3757 + 86 + 

SELECT COUNT(1),NTB.CATEGORY_TS FROM RSA_EGARANT.NSI_TARIFF_BASE ntb WHERE NTB.IS_ACTIVE = 1 AND NTB.INSURER_ID = 00000007 AND NTB.SYS_CORR_DATE >= TRUNC(sysdate) GROUP BY NTB.CATEGORY_TS;
\
SELECT * FROM RSA_EGARANT.INS_COMPANY "ic" 
JOIN RSA_EGARANT."USER" u ON "ic".INS_COMPANY_ID = u.INS_COMPANY_ID
WHERE "ic".INS_COMPANY_ID = 206;

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR "ppj" WHERE "ppj".INS_REQ_JOUR_ID = '1514200465' ORDER BY "ppj".PROC_QUEUE_DATE;

SELECT * FROM RSA_EGARANT.NSI_REASON_REJECT_SUMMARY "nrrs";
SELECT * FROM RSA_EGARANT.NSI_REASON_REJECTION "nrr";

SELECT
*
FROM RSA_egarant.NSI_TARIFF_BASE_LIMIT "ntbl"
JOIN RSA_EGARANT.NSI_VEHICLE_CATEGORY_EXTENDED "nvce" ON "ntbl".VEHICLE_CATEGORY_EXT_ID = "nvce".VEHICLE_CATEGORY_EXT_ID;

SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR "ppj" WHERE "ppj".INS_REQ_JOUR_ID = '160807194';

SELECT * FROM RSA_EGARANT.kladr k WHERE K.END_DATE = TO_DATE('01.01.9000','dd.mm.yyyy') AND code = '5001400000000';

SELECT * FROM RSA_EGARANT.NSI_KT "nk";

SELECT
*
FROM RSA_EGARANT.NSI_TARIFF_BASE ntb
WHERE ntb.IS_ACTIVE = 1
AND ntb.INSURER_ID = 00000007
AND ntb.BEG_DATE >= TRUNC(SYSDATE + 1)
AND ntb.CATEGORY_TS = 'A'
AND ntb.KLADR NOT IN (
SELECT
K.CODE
FROM RSA_EGARANT.KLADR k
WHERE K.KT_ID IN (
SELECT
NK.KT_ID
FROM RSA_EGARANT.NSI_KT nk 
WHERE NK.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy')
/*
AND NK.KT_ID NOT IN (
SELECT K.KT_ID FROM RSA_EGARANT.KLADR k WHERE substr(K.CODE,3,13) = 00000000000 AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy') AND K.KT_ID IS NOT NULL
)*/ AND NK.PLACE != 'Прочие города и населенные пункты'
)
AND k.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy') 
)

;

WITH TT1 AS (
              sELECT k.code--,K.END_DATE
              FROM kladr k
             WHERE regexp_like(k.code, '^\d{2}0+$') AND K.END_DATE = TO_DATE('01.01.9000','dd.mm.yyyy')
            UNION
            SELECT k.code--,KT.END_DATE
              FROM rsa_egarant.nsi_kt kt
              JOIN rsa_egarant.kladr k
                ON k.kt_id = kt.kt_id
             WHERE kt.place != 'Прочие города и населенные пункты' AND K.END_DATE = TO_DATE('01.01.9000','dd.mm.yyyy') AND kt.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy')

) 
SELECT count(1) /*,
TO_CHAR(end_date,'dd.mm.yyyy')*/
FROM TT1;
/*GROUP BY TO_CHAR(end_date,'dd.mm.yyyy');*/

SELECT * FROM RSA_EGARANT.NSI_KT nk;

  SELECT DISTINCT K.CODE--,KT.END_DATE
              FROM rsa_egarant.nsi_kt kt
              JOIN rsa_egarant.kladr k
                ON k.kt_id = kt.kt_id
             WHERE kt.place != 'Прочие города и населенные пункты' --AND K.END_DATE = TO_DATE('01.01.9000','dd.mm.yyyy') AND kt.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy')

-- с условием  AND K.END_DATE = TO_DATE('01.01.9000','dd.mm.yyyy') AND kt.END_DATE = TO_DATE('01.01. 9000','dd.mm.yyyy') 3573
-- без условия 4497

SELECT * FROM RSA_EGARANT.INS_REQUEST_JOUR irj WHERE IRJ.INS_COMPANY_ID = 269 AND IRJ.BEG_DATE >= TRUNC(sysdate);