WITH TT1 AS (
SELECT
IRJ.INS_REQ_JOUR_ID,IRJ.REQ_BODY,irj.RESP_BODY,IRJ.BEG_DATE,IRJ.END_DATE
FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
JOIN RSA_EOSAGO.INS_COMPANY ic ON IRJ.INS_COMPANY_ID = IC.INS_COMPANY_ID
WHERE ic.INSURER_ID = '20400000'
AND irj.REQ_TYPE_ID IN ('72')
AND irj.REQ_STATUS_ID = 3
AND beg_date >= TO_DATE ('03.12.2019 00:00:00','dd.mm.yyyy hh24:mi:ss')
and beg_date <= TO_DATE ('04.12.2019 23:59:59','dd.mm.yyyy hh24:mi:ss')
AND IRJ.REQ_BODY IS NOT NULL
),
TT2 as (
SELECT
INS_REQ_JOUR_ID,
REQ_BODY,
BEG_DATE,
END_DATE,
EXTRACTVALUE(VALUE(CC1),'EpolicyID') AS BLOB_EPOLICY,
EXTRACTVALUE(VALUE(CC2),'Message') AS Message
--UTL_COMPRESS.LZ_UNCOMPRESS(req_body),
--TO_number(EXTRACTVALUE(XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(req_body),NLS_CHARSET_ID('UTF8')),'*:AcceptScanRequest/ListAppScanRequest/ApplicationData/EpolicyID')) as BLOB_EPOLICY
FROM tt1,
TABLE(XMLSEQUENCE(EXTRACT(XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(req_body),NLS_CHARSET_ID('AL32UTF8')),'*:AcceptScanRequest/ListAppScanRequest/ApplicationData/EpolicyID'))) CC1,
TABLE(XMLSEQUENCE(EXTRACT(XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(resp_body),NLS_CHARSET_ID('AL32UTF8')),'*:AcceptScanResponse/ListAppScanResponse/ApplicationRespData/ErrorList/ErrorInfo/Message'))) CC2
)
SELECT
*
FROM tt2  WHERE BLOB_EPOLICY = '2844225005'
;


--WHERE INS_REQ_JOUR_ID = '2843635795'
--WHERE 
--EXTRACTVALUE(XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(req_body),NLS_CHARSET_ID('UTF8')),'*:AcceptScanRequest/ListAppScanRequest/ApplicationData/EpolicyID')= 2844225005;
--