SELECT * FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj WHERE PPJ.INS_REQ_JOUR_ID = '1517037992';

SELECT * FROM RSA_EOSAGO.NSI_DIRECTORY_MOD_MODEL ndmm
JOIN RSA_EOSAGO.NSI_MODEL nm ON NDMM.MODEL_ID = NM.MODEL_ID
JOIN RSA_EOSAGO.NSI_BRAND nb ON NM.BRAND_ID = NB.BRAND_ID
WHERE NDMM.MODEL_ID = '206021977';

SELECT * FROM RSA_EOSAGO.user_rsa
JOIN RSA_EOSAGO.USER_ROLE ur ON RSA_EOSAGO.USER_RSA.USER_ROLE_ID = UR.USER_ROLE_ID
JOIN RSA_EOSAGO.USER_ACCESS_DATA uad ON UR.USER_ROLE_ID = UAD.USER_ROLE_ID;

SELECT * FROM RSA_EOSAGO.USER_ACCESS_DATA "uad";

SELECT * FROM RSA_EOSAGO.USER_RSA ur;

SELECT * FROM RSA_EOSAGO.USER_ROLE "ur";

INSERT INTO RSA_EOSAGO.USER_RSA VALUES (
user_rsa_sequence.nextval,
'zorenkoiv',
'DistributionBoss4',
14
);

COMMIT;

INSERT INTO RSA_EOSAGO.USER_ACCESS_DATA VALUES (
USER_ACCESS_DATA_SEQUENCE.NEXTVAL,
14,
0,
0,
1,
0,
0,
1,
1
);

COMMIT;

INSERT INTO rsa_eosago.USER_ROLE VALUES(
14,
'DistributionUpload',
0,
1,
SYSDATE,
SYSDATE,
1
);