SELECT * FROM RSA_EGARANT.ins_company ic WHERE ins_company_id = '39';

INSERT INTO RSA_EGARANT.INS_COMPANY (
INS_COMPANY_ID,
INS_COMPANY,
INSURER_ID,
CREATE_DATE,
CHANGE_DATE,
SYS_CORR_DATE,
DOMAIN_NAME
) VALUES (
39,
'Либерти Страхование (АО)',
'08100001',
SYSDATE,
SYSDATE,
SYSDATE,
'kfins'
);
COMMIT;


--228	Либерти Страхование (АО)	08100000

SELECT * FROM RSA_EGARANT."USER" "u" WHERE "u".INS_COMPANY_ID = 39;

INSERT INTO RSA_EGARANT."USER" (
USER_ID,
USER_ROLE_ID,
INS_COMPANY_ID,
LOGIN,
PASSWORD,
CREATE_DATE,
CHANGE_DATE,
AUTHOR
) VALUES (
39,
1,
39,
08100001,
'LBT987ty',
SYSDATE,
SYSDATE,
1
);

COMMIT;

SELECT * FROM RSA_EGARANT.INS_COMP_PAYMENT_ACCOUNT "icpa" WHERE "icpa".INS_COMPANY_ID = 39;

INSERT INTO RSA_EGARANT.INS_COMP_PAYMENT_ACCOUNT (
INS_COMPANY_ID,
LOGIN,
PASSWORD
) VALUES (
39,
'autoins-api',
'autoins'
);
COMMIT;

-------------------------------

SELECT * FROM RSA_EOSAGO.INS_COMPANY ic WHERE IC.INSURER_ID = '08100000';

--39	ЛИБЕРТИ СТРАХОВАНИЕ	08100000

SELECT * FROM RSA_EOSAGO."USER" u WHERE U.INS_COMPANY_ID = 39;

SELECT * FROM RSA_EOSAGO.POLICY_NUMBERS "pn" WHERE "pn".INS_COMPANY_ID = 39;

SELECT * FROM RSA_EOSAGO.INSURER_REGION "ir" WHERE "ir".INS_COMPANY_ID = 39;

SELECT * FROM RSA_EOSAGO.INS_REQUEST_JOUR "irj" WHERE "irj".INS_COMPANY_ID = 39 AND "irj".BEG_DATE >= TRUNC(sysdate);