SELECT 
DISTINCT
--V.VEHICLE_REC_ID,
V.VIN,
V.LICENSE_PLATE,
ic.INS_COMPANY,
po.BSO_FULL_NUM
FROM rsa2.vehicle v 
JOIN rsa2.VEHICLE_NON_IDENTIFYING vni ON V.VEHICLE_REC_ID = VNI.VEHICLE_REC_ID
JOIN rsa1.POLICY_OSAGO po ON VNI.VEHICLE_NON_IDENTIFYING_REC_ID = PO.VEHICLE_NON_IDENTIFYING_REC_ID
JOIN rsa1.INS_COMPANY ic ON PO.INS_COMPANY_ID = IC.INS_COMPANY_ID
WHERE V.LICENSE_PLATE = 'К540АА56';

SELECT * FROM rsa1.VEHICLE_VALIDATION "vv" WHERE "vv".VEHICLE_VALIDATION_VALUE = 'б';

--(SELECT REGEXP_SUBSTR('ХТК412ИЭ0R0402416','',1,LEVEL)) 1 FROM DUAL d CONNECT BY LEVEL <= REGEXP_COUNT('ХТК412ИЭ0R0402416',',')+1;


WITH TT1 AS (
SELECT REGEXP_SUBSTR('ХТJ11113Б20071188','\w',1,LEVEL) FROM DUAL d CONNECT BY LEVEL <= REGEXP_COUNT('ХТJ11113Б20071188','\w')
)
SELECT * FROM rsa1.VEHICLE_NORMALIZ_RULE vnr WHERE vnr.INITIAL_DATA IN (
SELECT * FROM tt1
);

SELECT normalizestring('ХТК412ИЭ0R0402416') FROM DUAL "d";

SELECT * FROM rsa1.VEHICLE_NORMALIZ_RULE "vnr" WHERE "vnr".INITIAL_DATA = '';

SELECT * FROM rsa2.VEHICLE_NORMALIZ "vn";

SELECT "v".VEHICLE_REC_ID FROM rsa2.VEHICLE "v" WHERE vin = 'XTJ11113B20071188';

SELECT NORMALIZESTRING('ХТJ11113Б20071188') FROM dual;