SELECT
*
FROM rsa1.PERSONAL_INFO pi
WHERE lower(PI.LAST_NAME)=lower('СИДОРЕНОК')
AND LOWER(pi.FIRST_NAME)=lower('ДЕНИС') 
AND lower(PI.MIDDLE_NAMES)=lower('ВАСИЛЬЕВИЧ')
AND PI.BIRTH_DATE = TO_DATE('15.02.1979','dd.mm.yyyy');

--2BA8497A1B90BDC47857BE94A487249FBAC3901BF3B730C8169FCE484A9ECCE2

SELECT
irj.INS_COMPANY_ID,
IRJ.INS_REQ_ID,
IRJ.REQ_TYPE_ID,
irj.BEG_DATE,
irj.END_DATE,
XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.req_body),NLS_CHARSET_ID('UTF8')) REQ_XML,
XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(irj.resp_body),NLS_CHARSET_ID('UTF8')) RESP_XML
FROM rsa2.KBM_JOUR kj
JOIN rsa2.KBM_PHYSICAL_PERSON_CALC kppc ON KJ.KBM_PHYSICAL_PERSON_CALC_ID = KPPC.KBM_PHYSICAL_PERSON_CALC_ID
JOIN rsa2.KBM_PHYSICAL_PERSON kpp ON KPPC.KBM_PHYSICAL_PERSON_CALC_ID = KPP.KBM_PHYSICAL_PERSON_CALC_ID
JOIN rsa2.SUBJECT_OSAGO so ON KPP.SUBJ_OSAGO_REC_ID = SO.SUBJ_OSAGO_REC_ID
JOIN rsa1.INS_REQUEST_JUR irj ON KJ.INS_REQ_ID = IRJ.INS_REQ_ID
WHERE SO.SUBJ_HASH = '2BA8497A1B90BDC47857BE94A487249FBAC3901BF3B730C8169FCE484A9ECCE2'
AND IRJ.INS_COMPANY_ID = 19;