SELECT * FROM rsa_eosago.REQUEST_TYPE "rt" ORDER BY req_type_id;

---73	Запрос на получение списка договоров е-ОСАГО, заключенных в Модуле «Гарантия е-ОСАГО» от имени СК

---79	Запрос на получение копий документов по заявлению


SELECT
COUNT(IRJ.INS_REQ_JOUR_ID),
IRJ.REQ_TYPE_ID
FROM RSA_EOSAGO.INS_REQUEST_JOUR irj
WHERE IRJ.REQ_TYPE_ID IN (73,79)
AND IRJ.INS_COMPANY_ID = 19
AND IRJ.BEG_DATE >= TRUNC(SYSDATE - 1)
AND IRJ.BEG_DATE < TRUNC(sysdate)
GROUP BY IRJ.REQ_TYPE_ID;

--5172	79
--284	73
WITH TT AS (
SELECT 
IRJ.INS_REQ_JOUR_ID,
IRJ.REQ_TYPE_ID,
irj.REQ_BODY,
irj.BEG_DATE,
irj.END_DATE,
EXTRACTVALUE(VALUE(TT1),'ScanID') as SCANID
FROM RSA_EOSAGO.INS_REQUEST_JOUR irj,
TABLE(XMLSEQUENCE(EXTRACT(XMLTYPE(UTL_COMPRESS.LZ_UNCOMPRESS(req_body),NLS_CHARSET_ID('AL32UTF8')),'*:GetScanRequest/ScanID'))) TT1
WHERE IRJ.REQ_TYPE_ID IN (79)
AND IRJ.INS_COMPANY_ID = 19
AND IRJ.BEG_DATE >= TRUNC(SYSDATE - 1)
AND IRJ.BEG_DATE < TRUNC(sysdate)
)
SELECT COUNT(INS_REQ_JOUR_ID),SCANID FROM TT GROUP BY SCANID;