SELECT * FROM RSA_EOSAGO.epolicy e WHERE E.POLICY_NUMBER = '0101208298';

SELECT
E.POLICY_INS_REQ_JOUR_ID,E.POLICY_FULL_NUM 
FROM RSA_EOSAGO.POLICY_PROCESS_JOUR ppj
JOIN RSA_EOSAGO.EPOLICY e ON PPJ.POLICY_PROC_ID = E.POLICY_PROC_ID
WHERE PPJ.INS_COMPANY_ID = 223
AND PPJ.PROC_QUEUE_DATE >= TRUNC(SYSDATE,'yyyy')
AND E.IS_EGARANT = 1
AND E.IS_TECH_COR = 0
AND E.RECALL_POLICY_UNQ_ID = 0;

SELECT
ic.INS_COMPANY,
ic.INSURER_ID,
e.INS_COMP_DRAFT_POLICY_ID,
e.POLICY_FULL_NUM,
E.POLICY_CREATE_DATE,
E.POLICY_BEG_DATE,
E.POLICY_END_DATE,
E.POLICY_INS_REQ_JOUR_ID,
E.POLICY_STATE_ID,
E.IS_EGARANT
FROM RSA_EOSAGO.EPOLICY e
JOIN RSA_EOSAGO.INS_COMPANY ic ON E.INS_COMPANY_ID = IC.INS_COMPANY_ID
WHERE E.POLICY_INS_REQ_JOUR_ID IN (
'2780884201',
'2773732496',
'2453917029',
'2781392825',
'2781336235',
'2781200194',
'2780890029',
'2780716651',
'2780268414',
'2780215355',
'2773720109',
'2773100423',
'2308972870',
'2307901336'
) AND E.RECALL_POLICY_UNQ_ID = 0 AND E.IS_TECH_COR = 0 AND E.POLICY_TERMIN_DATE IS null;


SELECT * FROM rsa_eosago.EPOLICY "e" WHERE "e".INS_COMPANY_ID = 223 AND "e".POLICY_CREATE_DATE >= TRUNC(SYSDATE - 1) AND "e".IS_EGARANT = 1 AND "e".POLICY_STATE_ID = 1;


SELECT * FROM RSA_EOSAGO.EPOLICY "e" WHERE "e".POLICY_INS_REQ_JOUR_ID = '2780268414';

WITH EGARANT_RETURN AS (
SELECT DISTINCT APPLICATION_ID,POLICY_REC_ID,POLICY_NUM_OPERATION_ID FROM RSA_EOSAGO.vacant_policy_counter_return WHERE INSURER_ID = '12600000'
)
SELECT
ic.INS_COMPANY,
ic.INSURER_ID,
E.INS_COMP_DRAFT_POLICY_ID,
E.POLICY_FULL_NUM,
E.POLICY_CREATE_DATE,
E.POLICY_BEG_DATE,
E.POLICY_END_DATE,
E.IS_EGARANT,
E.POLICY_STATE_ID,
E.RECALL_POLICY_UNQ_ID,
E.POLICY_TERMIN_DATE,
POLICY_NUM_OPERATION_ID
FROM EGARANT_RETURN
JOIN RSA_EOSAGO.EPOLICY e ON EGARANT_RETURN.POLICY_REC_ID = E.POLICY_REC_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON E.INS_COMPANY_ID = IC.INS_COMPANY_ID
WHERE POLICY_NUM_OPERATION_ID = 1;




sELECT * FROM RSA_EOSAGO.vacant_policy_counter_return WHERE INSURER_ID = '02000000' ORDER BY VACANT_POLICY_COUNT_RETURN_ID;

SELECT * FROM RSA_EGARANT.vac

SELECT * FROM RSA_EOSAGO.EPOLICY e WHERE E.POLICY_INS_REQ_JOUR_ID = '2781392825';


WITH EGARANT_RETURN AS (
SELECT DISTINCT APPLICATION_ID,POLICY_REC_ID,POLICY_NUM_OPERATION_ID FROM RSA_EOSAGO.vacant_policy_counter_return WHERE INSURER_ID = '02000000'
)
SELECT
ic.INS_COMPANY,
ic.INSURER_ID,
E.INS_COMP_DRAFT_POLICY_ID,
E.POLICY_FULL_NUM,
E.POLICY_CREATE_DATE,
E.POLICY_BEG_DATE,
E.POLICY_END_DATE,
E.IS_EGARANT,
E.POLICY_STATE_ID,
E.RECALL_POLICY_UNQ_ID,
E.POLICY_TERMIN_DATE,
POLICY_NUM_OPERATION_ID
FROM EGARANT_RETURN
JOIN RSA_EOSAGO.EPOLICY e ON EGARANT_RETURN.POLICY_REC_ID = E.POLICY_REC_ID
JOIN RSA_EOSAGO.INS_COMPANY ic ON E.INS_COMPANY_ID = IC.INS_COMPANY_ID
WHERE POLICY_NUM_OPERATION_ID = 1;

SELECT * FROM RSA_EGARANT.EGARANT_SETTINGS "es";

SELECT * FROM RSA_EGARANT.EVENT_LOG el
LEFT JOIN RSA_EGARANT.EVENT_TYPE et ON EL.EVENT_TYPE_ID = ET.EVENT_TYPE_ID
 WHERE APPLICATION_ID = '2781392825' ORDER BY EL.EVENT_DATE;