WITH TT1 AS (
SELECT
kjv.VEHICLE_NORMALIZ_REC_ID,
kjv.VEHICLE_LP_NORMALIZ_REC_ID,
kjv.JURIDICAL_VEHICLE_KBM_ID,
kjv.POLICY_REC_ID
FROM RSA2.KBM_JURIDICAL_PERSON_CALC kjpc
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
WHERE kjpc.KBM_JURIDICAL_PERSON_CALC_ID = 2497800
),
TT2 AS (
SELECT
kjv.VEHICLE_NORMALIZ_REC_ID,
kjv.VEHICLE_LP_NORMALIZ_REC_ID,
kjv.JURIDICAL_VEHICLE_KBM_ID,
kjv.POLICY_REC_ID
FROM RSA2.KBM_JURIDICAL_PERSON_CALC kjpc
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
WHERE kjpc.KBM_JURIDICAL_PERSON_CALC_ID = 2497800
),
TT3 AS (
SELECT
*
FROM TT1
MINUS
SELECT
*
FROM TT2
)
SELECT
ic.INS_COMPANY,
ic.INSURER_ID,
ppj.BSO_NUMBER,
ppj.INS_COMP_POLICY_ID,
ppj.PROC_QUEUE_DATE,
ppj.REQ_STATUS_ID,
ppj.HANDLE_TYPE_ID,
ht.HANDLE_NAME,
tt3.*
FROM TT3 
JOIN rsa1.POLICY_PROCESS_JUR ppj ON TT3.POLICY_REC_ID = PPJ.POLICY_REC_ID
JOIN rsa1.HANDLE_TYPE ht ON PPJ.HANDLE_TYPE_ID = HT.HANDLE_TYPE_ID
JOIN rsa1.INS_COMPANY ic ON PPJ.INS_COMPANY_ID = IC.INS_COMPANY_ID
;