WITH TT1 AS (
SELECT
kjv.VEHICLE_NORMALIZ_REC_ID,
kjv.VEHICLE_LP_NORMALIZ_REC_ID,
kjv.JURIDICAL_VEHICLE_KBM_ID,
kjv.POLICY_REC_ID
FROM RSA2.KBM_JURIDICAL_PERSON_CALC kjpc
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
WHERE kjpc.KBM_JURIDICAL_PERSON_CALC_ID = 2497800
),
TT2 AS (
SELECT
kjv.VEHICLE_NORMALIZ_REC_ID,
kjv.VEHICLE_LP_NORMALIZ_REC_ID,
kjv.JURIDICAL_VEHICLE_KBM_ID,
kjv.POLICY_REC_ID
FROM RSA2.KBM_JURIDICAL_PERSON_CALC kjpc
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
WHERE kjpc.KBM_JURIDICAL_PERSON_CALC_ID = 2497800
)
SELECT
TT2.VEHICLE_NORMALIZ_REC_ID,
TT2.VEHICLE_LP_NORMALIZ_REC_ID,
TT2.JURIDICAL_VEHICLE_KBM_ID,
TT2.POLICY_REC_ID,
TT1.VEHICLE_NORMALIZ_REC_ID,
TT1.VEHICLE_LP_NORMALIZ_REC_ID,
TT1.JURIDICAL_VEHICLE_KBM_ID,
TT1.POLICY_REC_ID
FROM TT2 JOIN TT1 ON tt2.VEHICLE_NORMALIZ_REC_ID = tt1.VEHICLE_NORMALIZ_REC_ID
WHERE TT1.JURIDICAL_VEHICLE_KBM_ID != TT2.JURIDICAL_VEHICLE_KBM_ID
UNION
SELECT
TT2.VEHICLE_NORMALIZ_REC_ID,
TT2.VEHICLE_LP_NORMALIZ_REC_ID,
TT2.JURIDICAL_VEHICLE_KBM_ID,
TT2.POLICY_REC_ID,
TT1.VEHICLE_NORMALIZ_REC_ID,
TT1.VEHICLE_LP_NORMALIZ_REC_ID,
TT1.JURIDICAL_VEHICLE_KBM_ID,
TT1.POLICY_REC_ID
FROM TT1 JOIN TT2 ON TT1.VEHICLE_LP_NORMALIZ_REC_ID = TT2.VEHICLE_LP_NORMALIZ_REC_ID
WHERE TT1.JURIDICAL_VEHICLE_KBM_ID != TT2.JURIDICAL_VEHICLE_KBM_ID;

SELECT MAX(kj.INS_REQ_ID)
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
--JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' /*AND kj.INS_REQ_ID = '7941691398'*/
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy') 
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy')
AND KJ.KBM_JURIDICAL_PERSON_CALC_ID = 2497800;

SELECT count(1)
FROM RSA2.KBM_JOUR kj
JOIN RSA2.KBM_JURIDICAL_PERSON_CALC kjpc ON kj.KBM_JURIDICAL_PERSON_CALC_ID = kjpc.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_JURIDICAL_VEHICLE kjv ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kjv.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.KBM_ENTITY_STATUS kes ON kjpc.KBM_JURIDICAL_PERSON_CALC_ID = kes.KBM_JURIDICAL_PERSON_CALC_ID
JOIN RSA2.SUBJECT_OSAGO so ON kj.MAIN_SUBJ_OSAGO_REC_ID = so.SUBJ_OSAGO_REC_ID
JOIN RSA2.KBM_CHANGE_STATUS_DATA kcsd ON kes.KBM_CHANGE_STATUS_DATA_ID = kcsd.KBM_CHANGE_STATUS_DATA_ID
WHERE  so.INN = '7709378229' /*AND kj.INS_REQ_ID = '7941691398'*/
AND kjpc.CREATE_DATE >= TO_DATE('09.09.2019','dd.mm.yyyy') 
AND  kjpc.CREATE_DATE < TO_DATE('10.09.2019','dd.mm.yyyy')
AND kj.INS_REQ_ID = '7924103654';
